/* ══════════════════════════════════════════════════════════════
   Whisky Collector — 내장 지식 베이스 (자동 초안용)
   · 여기 있는 값은 모두 "초안"입니다. 앱은 이 값을 채운 뒤
     사용자가 확인·수정하도록 표시합니다.
   · 평점은 참고값(≈), 가격은 국내 시장 추정 범위(원)입니다.
   ══════════════════════════════════════════════════════════════ */

/* 지역별 일반 하우스 스타일 — 브랜드 정보가 없을 때의 폴백 */
const REGION_STYLE = {
  'Islay':       {nose:'피트 스모크, 요오드, 해조, 소금기', taste:'스모키한 풍미, 짠맛, 후추, 시트러스', finish:'길고 스모키한 마무리'},
  'Speyside':    {nose:'사과·서양배, 꿀, 옅은 오크 바닐라', taste:'과실감, 몰트, 바닐라, 부드러운 단맛', finish:'중간 길이의 깔끔한 마무리'},
  'Highland':    {nose:'꿀, 헤더, 말린 과일, 오크', taste:'몰트 단맛, 스파이스, 견과, 과실', finish:'중간~긴 길이, 따뜻한 스파이스'},
  'Island':      {nose:'옅은 스모크, 바닷바람, 후추', taste:'몰티한 단맛과 은근한 피트, 검은 후추', finish:'중간~긴 길이, 스모키한 잔향'},
  'Lowland':     {nose:'풀, 레몬, 시리얼, 꽃향', taste:'가볍고 산뜻한 몰트, 시트러스', finish:'짧고 드라이한 마무리'},
  'Campbeltown': {nose:'바닷바람, 기름진 몰트, 옅은 피트', taste:'짭짤한 몰트, 오일리한 질감, 과실', finish:'길고 복합적인 마무리'},
  'Kentucky':    {nose:'바닐라, 캐러멜, 옥수수 단맛, 오크', taste:'캐러멜, 바닐라, 라이 스파이스, 구운 오크', finish:'중간 길이, 달콤한 오크'},
  'Japan':       {nose:'과실, 꿀, 옅은 백단, 정갈한 오크', taste:'섬세한 과실과 몰트, 은은한 스파이스', finish:'깔끔하고 여운이 정돈된 마무리'},
  'Ireland':     {nose:'배·사과, 크림, 시리얼', taste:'부드러운 과실과 바닐라, 크리미한 질감', finish:'짧고 매끄러운 마무리'},
  'Taiwan':      {nose:'열대 과일, 코코넛, 바닐라', taste:'농익은 과실, 진한 오크, 단맛', finish:'중간~긴 길이, 달콤한 오크'},
  'default':     {nose:'과실, 몰트, 오크', taste:'몰트 단맛과 오크의 균형', finish:'중간 길이의 마무리'},
};

/* 브랜드/증류소 ─ k: 키, ko/alias: 한글 검색어, wiki: 영문 위키 문서명 */
const BRANDS = [
  // ── Speyside
  {k:'glenfiddich', en:'Glenfiddich', ko:'글렌피딕', region:'Speyside', country:'스코틀랜드', wiki:'Glenfiddich',
   cask:'Ex-Bourbon American Oak + Ex-Sherry European Oak',
   house:{nose:'서양배, 풋사과, 옅은 오크 바닐라, 꽃향', taste:'배·사과의 과실감, 몰트 비스킷, 크리미한 바닐라', finish:'짧고 깔끔한 오크와 몰트의 마무리'}},
  {k:'macallan', en:'The Macallan', ko:'맥캘란', alias:['마카란','더 맥캘란'], region:'Speyside', country:'스코틀랜드', wiki:'Macallan_distillery',
   cask:'Sherry Seasoned European/American Oak',
   house:{nose:'건포도, 오렌지 껍질, 셰리, 진저', taste:'말린 과일, 셰리 단맛, 몰트, 스파이스', finish:'길고 풍성한 셰리 여운'}},
  {k:'glenlivet', en:'The Glenlivet', ko:'글렌리벳', alias:['더 글렌리벳'], region:'Speyside', country:'스코틀랜드', wiki:'Glenlivet_distillery',
   cask:'Ex-Bourbon + Ex-Sherry Oak',
   house:{nose:'파인애플, 배, 꽃향, 바닐라', taste:'부드러운 과실과 꿀, 크리미한 바닐라', finish:'중간 길이, 깔끔한 단맛'}},
  {k:'balvenie', en:'The Balvenie', ko:'발베니', alias:['더 발베니'], region:'Speyside', country:'스코틀랜드', wiki:'Balvenie_distillery',
   cask:'Ex-Bourbon + Ex-Sherry Oak (Finish)',
   house:{nose:'꿀, 바닐라, 오렌지, 몰트', taste:'진한 꿀 단맛, 견과, 시나몬', finish:'따뜻하고 긴 꿀·오크 여운'}},
  {k:'aberlour', en:'Aberlour', ko:'아벨라워', alias:['애버라워'], region:'Speyside', country:'스코틀랜드', wiki:'Aberlour_distillery',
   cask:'Ex-Bourbon + Oloroso Sherry Butt',
   house:{nose:'건포도, 체리, 시나몬, 다크초콜릿', taste:'진한 셰리 과실, 스파이스, 몰트 퍼지', finish:'길고 따뜻한 셰리 스파이스'}},
  {k:'glenallachie', en:'GlenAllachie', ko:'글렌알라키', alias:['글렌알라히'], region:'Speyside', country:'스코틀랜드', wiki:'GlenAllachie_distillery',
   cask:'PX/Oloroso Sherry Puncheon + Virgin Oak',
   house:{nose:'건포도, 무화과, 꿀, 진저브레드', taste:'셰리 과실, 몰트 퍼지, 계피·정향, 오렌지 껍질', finish:'길고 따뜻한 셰리 탄닌'}},
  {k:'glenfarclas', en:'Glenfarclas', ko:'글렌파클라스', region:'Speyside', country:'스코틀랜드', wiki:'Glenfarclas',
   cask:'Oloroso Sherry Cask',
   house:{nose:'셰리, 말린 과일, 몰트, 가죽', taste:'진한 셰리와 몰트, 크리스마스 케이크', finish:'길고 드라이한 셰리 마무리'}},
  {k:'craigellachie', en:'Craigellachie', ko:'크라이겔라키', region:'Speyside', country:'스코틀랜드', wiki:'Craigellachie_distillery',
   cask:'Ex-Bourbon + Sherry Cask',
   house:{nose:'파인애플, 유황 뉘앙스, 몰트, 밀랍', taste:'육중한 몰트, 열대 과일, 스모키한 뉘앙스', finish:'길고 오일리한 마무리'}},
  {k:'mortlach', en:'Mortlach', ko:'모틀라크', alias:['몰트락'], region:'Speyside', country:'스코틀랜드', wiki:'Mortlach_distillery',
   cask:'Sherry + Ex-Bourbon Cask',
   house:{nose:'육향(meaty), 셰리, 말린 과일, 가죽', taste:'묵직한 몰트와 셰리, 후추, 고기 육수 뉘앙스', finish:'매우 길고 육중한 마무리'}},
  {k:'benriach', en:'BenRiach', ko:'벤리악', region:'Speyside', country:'스코틀랜드', wiki:'BenRiach_distillery',
   cask:'Ex-Bourbon + Sherry + Virgin Oak',
   house:{nose:'과일 잼, 꿀, 옅은 피트, 바닐라', taste:'열대 과일, 몰트 단맛, 은근한 스모크', finish:'중간~긴 길이, 달콤한 오크'}},
  {k:'glengrant', en:'Glen Grant', ko:'글렌그란트', region:'Speyside', country:'스코틀랜드', wiki:'Glen_Grant_distillery',
   cask:'Ex-Bourbon Oak',
   house:{nose:'사과, 헤이즐넛, 바닐라', taste:'가볍고 산뜻한 몰트, 견과, 배', finish:'짧고 깔끔한 마무리'}},
  {k:'tamdhu', en:'Tamdhu', ko:'탐두', region:'Speyside', country:'스코틀랜드', wiki:'Tamdhu_distillery',
   cask:'100% Sherry Seasoned Oak',
   house:{nose:'셰리, 건포도, 오렌지, 토피', taste:'셰리 과실과 몰트, 부드러운 스파이스', finish:'중간~긴 길이의 셰리 여운'}},
  {k:'cragganmore', en:'Cragganmore', ko:'크라간모어', region:'Speyside', country:'스코틀랜드', wiki:'Cragganmore_distillery',
   cask:'Ex-Bourbon + Sherry Cask',
   house:{nose:'복합적인 허브, 꿀, 말린 과일', taste:'몰트 단맛, 견과, 옅은 스모크', finish:'중간 길이, 드라이한 마무리'}},
  {k:'benromach', en:'Benromach', ko:'벤로막', region:'Speyside', country:'스코틀랜드', wiki:'Benromach_distillery',
   cask:'Ex-Bourbon + Sherry Cask (약한 피트)',
   house:{nose:'옅은 피트, 붉은 과일, 몰트, 가죽', taste:'몰티한 단맛과 은근한 스모크, 셰리', finish:'중간 길이, 스모키한 잔향'}},
  {k:'glenmoray', en:'Glen Moray', ko:'글렌모레이', region:'Speyside', country:'스코틀랜드', wiki:'Glen_Moray_distillery',
   cask:'Ex-Bourbon Oak',
   house:{nose:'바닐라, 시트러스, 몰트', taste:'가벼운 과실과 바닐라, 시리얼', finish:'짧고 부드러운 마무리'}},
  {k:'speyburn', en:'Speyburn', ko:'스페이번', region:'Speyside', country:'스코틀랜드', wiki:'Speyburn_distillery',
   cask:'Ex-Bourbon + Sherry Cask',
   house:{nose:'사과, 토피, 시트러스', taste:'몰트 단맛, 과실, 바닐라', finish:'짧고 깔끔한 마무리'}},
  {k:'linkwood', en:'Linkwood', ko:'링크우드', region:'Speyside', country:'스코틀랜드', wiki:'Linkwood_distillery',
   cask:'Ex-Bourbon Oak',
   house:{nose:'꽃향, 사과, 레몬', taste:'섬세한 과실과 몰트, 크림', finish:'중간 길이, 우아한 마무리'}},
  {k:'strathisla', en:'Strathisla', ko:'스트라스아일라', region:'Speyside', country:'스코틀랜드', wiki:'Strathisla_distillery',
   cask:'Sherry + Ex-Bourbon Cask',
   house:{nose:'셰리, 말린 과일, 허브', taste:'진한 몰트와 셰리, 견과', finish:'중간~긴 길이의 마무리'}},

  // ── Highland
  {k:'glenmorangie', en:'Glenmorangie', ko:'글렌모렌지', alias:['글렌모린지'], region:'Highland', country:'스코틀랜드', wiki:'Glenmorangie_distillery',
   cask:'Ex-Bourbon Cask (+ 캐스크 피니시)',
   house:{nose:'시트러스, 복숭아, 바닐라, 꽃향', taste:'섬세한 과실과 바닐라, 크리미한 질감', finish:'중간 길이, 깔끔하고 우아한 마무리'}},
  {k:'dalmore', en:'The Dalmore', ko:'달모어', alias:['더 달모어'], region:'Highland', country:'스코틀랜드', wiki:'Dalmore_distillery',
   cask:'Ex-Bourbon + Oloroso Sherry Cask',
   house:{nose:'오렌지 마멀레이드, 초콜릿, 셰리', taste:'진한 셰리와 오렌지, 커피, 몰트', finish:'길고 진한 셰리·오크 여운'}},
  {k:'glendronach', en:'The GlenDronach', ko:'글렌드로낙', alias:['글렌드로나크','더 글렌드로낙'], region:'Highland', country:'스코틀랜드', wiki:'Glendronach_distillery',
   cask:'PX + Oloroso Sherry Cask',
   house:{nose:'건포도, 체리, 시나몬, 다크초콜릿', taste:'농밀한 셰리 과실, 몰트, 스파이스', finish:'길고 달콤한 셰리 마무리'}},
  {k:'oban', en:'Oban', ko:'오반', region:'Highland', country:'스코틀랜드', wiki:'Oban_distillery',
   cask:'Ex-Bourbon + Sherry Cask',
   house:{nose:'바닷바람, 시트러스, 꿀, 옅은 스모크', taste:'몰트 단맛과 짭짤함, 오렌지, 후추', finish:'중간 길이, 스모키한 소금기'}},
  {k:'clynelish', en:'Clynelish', ko:'클라이넬리시', region:'Highland', country:'스코틀랜드', wiki:'Clynelish_distillery',
   cask:'Ex-Bourbon Cask',
   house:{nose:'왁스, 시트러스, 옅은 스모크', taste:'오일리한 질감, 후추, 과실, 은근한 피트', finish:'길고 왁시한 마무리'}},
  {k:'oldpulteney', en:'Old Pulteney', ko:'올드풀트니', alias:['올드 풀트니'], region:'Highland', country:'스코틀랜드', wiki:'Old_Pulteney_distillery',
   cask:'Ex-Bourbon Cask',
   house:{nose:'바닷바람, 소금기, 시트러스', taste:'짭짤한 몰트, 배, 후추', finish:'중간 길이, 짠맛의 잔향'}},
  {k:'balblair', en:'Balblair', ko:'발블레어', region:'Highland', country:'스코틀랜드', wiki:'Balblair_distillery',
   cask:'Ex-Bourbon + Sherry Cask',
   house:{nose:'사과, 꿀, 바닐라, 시트러스', taste:'몰트 단맛과 과실, 스파이스', finish:'중간 길이의 부드러운 마무리'}},
  {k:'aberfeldy', en:'Aberfeldy', ko:'아버펠디', region:'Highland', country:'스코틀랜드', wiki:'Aberfeldy_distillery',
   cask:'Ex-Bourbon + Sherry Cask',
   house:{nose:'헤더 꿀, 시트러스, 몰트', taste:'진한 꿀 단맛, 과실, 스파이스', finish:'중간~긴 길이, 달콤한 마무리'}},
  {k:'glengoyne', en:'Glengoyne', ko:'글렌고인', region:'Highland', country:'스코틀랜드', wiki:'Glengoyne_distillery',
   cask:'Sherry + Ex-Bourbon Cask (무피트)',
   house:{nose:'사과, 셰리, 견과, 캐러멜', taste:'몰트 단맛과 셰리, 견과, 토피', finish:'중간 길이, 깔끔한 마무리'}},
  {k:'tomatin', en:'Tomatin', ko:'토마틴', region:'Highland', country:'스코틀랜드', wiki:'Tomatin_distillery',
   cask:'Ex-Bourbon + Sherry Cask',
   house:{nose:'사과, 바닐라, 몰트', taste:'부드러운 과실과 몰트, 오크', finish:'중간 길이의 마무리'}},
  {k:'dalwhinnie', en:'Dalwhinnie', ko:'달위니', region:'Highland', country:'스코틀랜드', wiki:'Dalwhinnie_distillery',
   cask:'Ex-Bourbon Cask',
   house:{nose:'헤더 꿀, 바닐라, 옅은 스모크', taste:'꿀과 몰트, 시트러스, 은근한 피트', finish:'중간 길이, 부드러운 마무리'}},
  {k:'deanston', en:'Deanston', ko:'딘스톤', region:'Highland', country:'스코틀랜드', wiki:'Deanston_distillery',
   cask:'Ex-Bourbon Cask',
   house:{nose:'꿀, 사과, 시리얼', taste:'몰트 단맛, 과실, 왁스', finish:'중간 길이의 마무리'}},
  {k:'edradour', en:'Edradour', ko:'에드라두어', region:'Highland', country:'스코틀랜드', wiki:'Edradour_distillery',
   cask:'Sherry Cask',
   house:{nose:'셰리, 붉은 과일, 몰트', taste:'진한 셰리와 몰트, 스파이스', finish:'중간~긴 길이의 셰리 여운'}},
  {k:'lochlomond', en:'Loch Lomond', ko:'로크로몬드', alias:['록로몬드'], region:'Highland', country:'스코틀랜드', wiki:'Loch_Lomond_distillery',
   cask:'Ex-Bourbon + Refill Cask',
   house:{nose:'배, 시트러스, 옅은 스모크', taste:'과실과 몰트, 은근한 피트', finish:'중간 길이의 마무리'}},

  // ── Islay
  {k:'ardbeg', en:'Ardbeg', ko:'아드벡', alias:['아드베그'], region:'Islay', country:'스코틀랜드', wiki:'Ardbeg_distillery',
   cask:'Ex-Bourbon Barrel (비냉각여과·무착색)',
   house:{nose:'짙은 피트 스모크, 타르, 레몬 제스트, 소금기', taste:'강렬한 스모크와 요오드, 라임, 흑후추, 다크초콜릿', finish:'매우 길고 스모키. 민트·타르의 잔향'}},
  {k:'laphroaig', en:'Laphroaig', ko:'라프로익', alias:['라프로익','라프로이그'], region:'Islay', country:'스코틀랜드', wiki:'Laphroaig_distillery',
   cask:'Ex-Bourbon Barrel',
   house:{nose:'요오드, 병원 소독약, 타르, 해조', taste:'강한 피트와 짠맛, 훈제 생선, 후추', finish:'길고 강렬한 스모크'}},
  {k:'lagavulin', en:'Lagavulin', ko:'라가불린', region:'Islay', country:'스코틀랜드', wiki:'Lagavulin_distillery',
   cask:'Ex-Bourbon + Sherry Cask',
   house:{nose:'짙은 피트, 타르, 셰리, 훈제향', taste:'농밀한 스모크와 단맛, 감초, 소금기', finish:'매우 길고 묵직한 스모크'}},
  {k:'bowmore', en:'Bowmore', ko:'보모어', region:'Islay', country:'스코틀랜드', wiki:'Bowmore_distillery',
   cask:'Ex-Bourbon + Sherry Cask',
   house:{nose:'옅은 피트, 바닷바람, 열대 과일, 카라멜', taste:'스모크와 과실의 균형, 소금기, 초콜릿', finish:'중간~긴 길이, 스모키한 단맛'}},
  {k:'bruichladdich', en:'Bruichladdich', ko:'브룩라디', alias:['브뤼클라딕'], region:'Islay', country:'스코틀랜드', wiki:'Bruichladdich_distillery',
   cask:'Ex-Bourbon + European Oak',
   house:{nose:'바닷바람, 보리, 시트러스, 꽃향 (무피트 라인)', taste:'몰트 단맛, 과실, 미네랄, 소금기', finish:'중간 길이, 깔끔한 마무리'}},
  {k:'caolila', en:'Caol Ila', ko:'쿨일라', alias:['카올일라','콜일라'], region:'Islay', country:'스코틀랜드', wiki:'Caol_Ila_distillery',
   cask:'Ex-Bourbon Cask',
   house:{nose:'스모크, 훈제 베이컨, 레몬, 해조', taste:'깔끔한 피트, 시트러스, 후추', finish:'중간~긴 길이, 드라이한 스모크'}},
  {k:'bunnahabhain', en:'Bunnahabhain', ko:'부나하벤', region:'Islay', country:'스코틀랜드', wiki:'Bunnahabhain_distillery',
   cask:'Sherry + Ex-Bourbon Cask (기본 무피트)',
   house:{nose:'셰리, 견과, 소금기, 말린 과일', taste:'몰트와 셰리, 짭짤함, 초콜릿', finish:'중간~긴 길이의 마무리'}},
  {k:'kilchoman', en:'Kilchoman', ko:'킬호만', region:'Islay', country:'스코틀랜드', wiki:'Kilchoman_distillery',
   cask:'Ex-Bourbon + Oloroso Sherry Cask',
   house:{nose:'신선한 피트, 레몬, 바닐라', taste:'젊고 활기찬 스모크, 시트러스, 크림', finish:'중간~긴 길이의 스모크'}},

  // ── Island / Lowland / Campbeltown
  {k:'talisker', en:'Talisker', ko:'탈리스커', region:'Island', country:'스코틀랜드', wiki:'Talisker_distillery',
   cask:'Ex-Bourbon + Refill Cask',
   house:{nose:'바닷바람, 후추, 스모크, 시트러스', taste:'후추의 매운맛, 스모크, 짠맛, 몰트', finish:'길고 후추향이 남는 스모키한 마무리'}},
  {k:'highlandpark', en:'Highland Park', ko:'하이랜드파크', alias:['하일랜드파크','하이랜드 파크'], region:'Island', country:'스코틀랜드', wiki:'Highland_Park_distillery',
   cask:'Sherry Seasoned European Oak + Ex-Bourbon',
   house:{nose:'헤더 꿀, 옅은 스모크, 셰리, 오렌지', taste:'꿀과 스모크의 균형, 말린 과일, 스파이스', finish:'중간~긴 길이, 헤더 스모크'}},
  {k:'jura', en:'Jura', ko:'주라', alias:['아일 오브 주라'], region:'Island', country:'스코틀랜드', wiki:'Jura_distillery',
   cask:'Ex-Bourbon + Sherry Cask',
   house:{nose:'소금기, 캐러멜, 옅은 스모크', taste:'몰트 단맛, 짭짤함, 은근한 피트', finish:'중간 길이의 마무리'}},
  {k:'arran', en:'Arran', ko:'아란', alias:['아이슬 오브 아란'], region:'Island', country:'스코틀랜드', wiki:'Arran_distillery',
   cask:'Ex-Bourbon + Sherry Cask',
   house:{nose:'시트러스, 바닐라, 사과', taste:'깔끔한 몰트와 과실, 크림', finish:'중간 길이의 마무리'}},
  {k:'springbank', en:'Springbank', ko:'스프링뱅크', region:'Campbeltown', country:'스코틀랜드', wiki:'Springbank_distillery',
   cask:'Ex-Bourbon + Sherry Cask',
   house:{nose:'바닷바람, 기름진 몰트, 옅은 피트, 배', taste:'짭짤한 몰트, 오일리한 질감, 과실, 스모크', finish:'길고 복합적인 마무리'}},
  {k:'glenscotia', en:'Glen Scotia', ko:'글렌스코시아', region:'Campbeltown', country:'스코틀랜드', wiki:'Glen_Scotia_distillery',
   cask:'Ex-Bourbon + Sherry Cask',
   house:{nose:'소금기, 바닐라, 시트러스', taste:'짭짤한 몰트, 과실, 옅은 스모크', finish:'중간~긴 길이의 마무리'}},
  {k:'auchentoshan', en:'Auchentoshan', ko:'오켄토션', alias:['아켄토션'], region:'Lowland', country:'스코틀랜드', wiki:'Auchentoshan_distillery',
   cask:'Ex-Bourbon + Sherry Cask (3회 증류)',
   house:{nose:'레몬, 시리얼, 바닐라, 꽃향', taste:'가볍고 산뜻한 몰트, 시트러스, 견과', finish:'짧고 드라이한 마무리'}},
  {k:'glenkinchie', en:'Glenkinchie', ko:'글렌킨치', region:'Lowland', country:'스코틀랜드', wiki:'Glenkinchie_distillery',
   cask:'Ex-Bourbon Cask',
   house:{nose:'풀, 레몬, 꽃향', taste:'가벼운 몰트와 시트러스, 시리얼', finish:'짧고 깔끔한 마무리'}},

  // ── Blends / Blended Malt
  {k:'johnniewalker', en:'Johnnie Walker', ko:'조니워커', alias:['조니 워커'], region:'Blend', country:'스코틀랜드', type:'Blended Scotch', wiki:'Johnnie_Walker',
   cask:'Ex-Bourbon + Sherry Cask (블렌딩)',
   house:{nose:'말린 과일, 옅은 스모크, 바닐라', taste:'몰트 단맛과 은근한 스모크, 스파이스', finish:'중간 길이의 스모키한 마무리'}},
  {k:'chivas', en:'Chivas Regal', ko:'시바스리갈', alias:['시바스 리갈'], region:'Blend', country:'스코틀랜드', type:'Blended Scotch', wiki:'Chivas_Regal',
   cask:'Ex-Bourbon + Sherry Cask (블렌딩)',
   house:{nose:'꿀, 사과, 바닐라', taste:'부드러운 몰트와 과실, 크림', finish:'중간 길이의 부드러운 마무리'}},
  {k:'ballantines', en:"Ballantine's", ko:'발렌타인', alias:['밸런타인'], region:'Blend', country:'스코틀랜드', type:'Blended Scotch', wiki:"Ballantine's_(whisky)",
   cask:'Ex-Bourbon + Sherry Cask (블렌딩)',
   house:{nose:'꿀, 시트러스, 옅은 스모크', taste:'몰트 단맛, 과실, 부드러운 오크', finish:'중간 길이의 마무리'}},
  {k:'famousgrouse', en:'The Famous Grouse', ko:'페이머스 그라우스', alias:['훼미리 그라우스','페이모스 그라우스'], region:'Blend', country:'스코틀랜드', type:'Blended Scotch', wiki:'The_Famous_Grouse',
   cask:'Ex-Bourbon + Sherry Cask (블렌딩)',
   house:{nose:'몰트, 시트러스, 토피', taste:'가벼운 몰트 단맛, 과실', finish:'짧고 깔끔한 마무리'}},
  {k:'monkeyshoulder', en:'Monkey Shoulder', ko:'몽키숄더', alias:['몽키 숄더'], region:'Speyside', country:'스코틀랜드', type:'Blended Malt', wiki:'Monkey_Shoulder',
   cask:'Ex-Bourbon Cask (몰트 3종 블렌딩)',
   house:{nose:'바닐라, 오렌지, 꿀, 몰트', taste:'부드러운 바닐라와 과실, 스파이스', finish:'중간 길이, 달콤한 마무리'}},
  {k:'compassbox', en:'Compass Box', ko:'컴퍼스박스', alias:['컴퍼스 박스'], region:'Blend', country:'스코틀랜드', type:'Blended Malt', wiki:'Compass_Box',
   cask:'Ex-Bourbon + French Oak (블렌딩)',
   house:{nose:'바닐라, 과실, 옅은 스모크', taste:'정교한 블렌딩의 과실과 오크', finish:'중간~긴 길이의 마무리'}},

  // ── Japan
  {k:'yamazaki', en:'Yamazaki', ko:'야마자키', region:'Japan', country:'일본', type:'Japanese Single Malt', wiki:'Yamazaki_distillery',
   cask:'American Oak + Spanish Oak + Mizunara',
   house:{nose:'복숭아·파인애플, 코코넛, 옅은 백단, 꿀', taste:'잘 익은 과일, 꿀, 시나몬, 미즈나라의 인센스', finish:'중간~긴 길이, 부드러운 오크와 스파이스'}},
  {k:'hakushu', en:'Hakushu', ko:'하쿠슈', region:'Japan', country:'일본', type:'Japanese Single Malt', wiki:'Hakushu_distillery',
   cask:'American Oak (+ 옅은 피트)',
   house:{nose:'풋사과, 민트, 허브, 옅은 스모크', taste:'상쾌한 과실과 민트, 은근한 피트', finish:'깔끔하고 청량한 마무리'}},
  {k:'yoichi', en:'Yoichi', ko:'요이치', region:'Japan', country:'일본', type:'Japanese Single Malt', wiki:'Yoichi_distillery',
   cask:'Ex-Bourbon + Sherry Cask (석탄 직화 증류)',
   house:{nose:'피트 스모크, 소금기, 붉은 과일', taste:'묵직한 스모크와 몰트, 후추, 과실', finish:'길고 스모키한 마무리'}},
  {k:'miyagikyo', en:'Miyagikyo', ko:'미야기쿄', region:'Japan', country:'일본', type:'Japanese Single Malt', wiki:'Miyagikyo_distillery',
   cask:'Ex-Bourbon + Sherry Cask',
   house:{nose:'붉은 과일, 셰리, 꽃향', taste:'섬세한 과실과 몰트, 크리미한 질감', finish:'중간 길이, 우아한 마무리'}},
  {k:'nikka', en:'Nikka', ko:'니카', alias:['닛카'], region:'Japan', country:'일본', type:'Japanese Blended', wiki:'Nikka_Whisky_Distilling',
   cask:'Ex-Bourbon + Sherry Cask (블렌딩)',
   house:{nose:'과실, 옅은 스모크, 바닐라', taste:'몰트와 과실의 균형, 스파이스', finish:'중간 길이의 마무리'}},
  {k:'hibiki', en:'Hibiki', ko:'히비키', region:'Japan', country:'일본', type:'Japanese Blended', wiki:'Hibiki_(whisky)',
   cask:'American/Spanish Oak + Mizunara (블렌딩)',
   house:{nose:'꿀, 오렌지, 화이트 초콜릿, 백단', taste:'섬세하고 부드러운 과실과 꿀, 미즈나라', finish:'길고 정갈한 마무리'}},
  {k:'chichibu', en:'Chichibu', ko:'치치부', region:'Japan', country:'일본', type:'Japanese Single Malt', wiki:'Chichibu_distillery',
   cask:'Ex-Bourbon + Mizunara + Sherry',
   house:{nose:'과실, 몰트, 미즈나라의 향신료', taste:'농축된 과실과 몰트, 스파이스', finish:'길고 복합적인 마무리'}},

  // ── USA
  {k:'makersmark', en:"Maker's Mark", ko:'메이커스마크', alias:['메이커스 마크'], region:'Kentucky', country:'미국', type:'Bourbon', wiki:"Maker's_Mark",
   cask:'New Charred American White Oak (Level 3 Char)',
   house:{nose:'바닐라, 캐러멜, 구운 빵, 체리', taste:'부드러운 캐러멜과 바닐라, 붉은 겨울밀의 단맛', finish:'짧고 스무스한 달콤한 오크'}},
  {k:'buffalotrace', en:'Buffalo Trace', ko:'버팔로트레이스', alias:['버팔로 트레이스'], region:'Kentucky', country:'미국', type:'Bourbon', wiki:'Buffalo_Trace_Distillery',
   cask:'New Charred American Oak',
   house:{nose:'바닐라, 캐러멜, 민트, 오크', taste:'캐러멜, 토피, 라이 스파이스, 다크초콜릿', finish:'중간 길이, 달콤하고 스파이시한 마무리'}},
  {k:'woodford', en:'Woodford Reserve', ko:'우드포드리저브', alias:['우드포드 리저브'], region:'Kentucky', country:'미국', type:'Bourbon', wiki:'Woodford_Reserve',
   cask:'New Charred American Oak',
   house:{nose:'말린 과일, 바닐라, 오렌지, 오크', taste:'풍부한 캐러멜과 과실, 스파이스, 코코아', finish:'길고 따뜻한 오크 마무리'}},
  {k:'wildturkey', en:'Wild Turkey', ko:'와일드터키', alias:['와일드 터키'], region:'Kentucky', country:'미국', type:'Bourbon', wiki:'Wild_Turkey_(bourbon)',
   cask:'New Charred American Oak (Alligator Char)',
   house:{nose:'캐러멜, 바닐라, 라이 스파이스, 오크', taste:'진한 캐러멜과 후추, 계피, 오크 탄닌', finish:'길고 스파이시한 마무리'}},
  {k:'fourroses', en:'Four Roses', ko:'포로지스', alias:['포 로지스'], region:'Kentucky', country:'미국', type:'Bourbon', wiki:'Four_Roses',
   cask:'New Charred American Oak',
   house:{nose:'붉은 과일, 꽃향, 바닐라, 라이', taste:'과실과 스파이스의 균형, 캐러멜', finish:'중간 길이, 스파이시한 마무리'}},
  {k:'eaglerare', en:'Eagle Rare', ko:'이글레어', alias:['이글 레어'], region:'Kentucky', country:'미국', type:'Bourbon', wiki:'Eagle_Rare',
   cask:'New Charred American Oak',
   house:{nose:'토피, 오렌지 껍질, 허브, 오크', taste:'캐러멜, 다크초콜릿, 가죽, 스파이스', finish:'길고 드라이한 오크 마무리'}},
  {k:'blantons', en:"Blanton's", ko:'블랑톤', alias:['블랜튼','블랑튼'], region:'Kentucky', country:'미국', type:'Bourbon', wiki:"Blanton's",
   cask:'New Charred American Oak (Single Barrel)',
   house:{nose:'바닐라, 캐러멜, 오렌지, 꿀', taste:'농밀한 캐러멜과 바닐라, 라이 스파이스', finish:'중간~긴 길이, 달콤한 오크'}},
  {k:'elijahcraig', en:'Elijah Craig', ko:'엘리야크레이그', alias:['엘리야 크레이그'], region:'Kentucky', country:'미국', type:'Bourbon', wiki:'Elijah_Craig_(bourbon)',
   cask:'New Charred American Oak',
   house:{nose:'바닐라, 캐러멜, 구운 오크, 훈연', taste:'진한 캐러멜과 오크, 스파이스, 초콜릿', finish:'길고 오키한 마무리'}},
  {k:'michters', en:"Michter's", ko:'믹터스', region:'Kentucky', country:'미국', type:'Bourbon', wiki:"Michter's",
   cask:'New Charred American Oak',
   house:{nose:'캐러멜, 바닐라, 붉은 과일', taste:'부드럽고 풍부한 캐러멜, 스파이스', finish:'중간~긴 길이의 마무리'}},
  {k:'knobcreek', en:'Knob Creek', ko:'노브크릭', alias:['노브 크릭'], region:'Kentucky', country:'미국', type:'Bourbon', wiki:'Knob_Creek',
   cask:'New Charred American Oak',
   house:{nose:'진한 바닐라, 캐러멜, 오크', taste:'묵직한 캐러멜과 오크, 후추', finish:'길고 강한 오크 마무리'}},
  {k:'jackdaniels', en:"Jack Daniel's", ko:'잭다니엘', alias:['잭 다니엘','잭다니엘스'], region:'Tennessee', country:'미국', type:'Tennessee Whiskey', wiki:"Jack_Daniel's",
   cask:'New Charred American Oak (숯 여과)',
   house:{nose:'바닐라, 캐러멜, 바나나, 오크', taste:'달콤한 캐러멜과 바닐라, 숯의 뉘앙스', finish:'중간 길이, 부드러운 마무리'}},

  // ── Ireland / World
  {k:'jameson', en:'Jameson', ko:'제임슨', region:'Ireland', country:'아일랜드', type:'Irish', wiki:'Jameson_Irish_Whiskey',
   cask:'Ex-Bourbon + Sherry Cask (3회 증류)',
   house:{nose:'배, 바닐라, 시리얼, 꽃향', taste:'부드러운 과실과 바닐라, 크리미한 질감', finish:'짧고 매끄러운 마무리'}},
  {k:'redbreast', en:'Redbreast', ko:'레드브레스트', alias:['레드 브레스트'], region:'Ireland', country:'아일랜드', type:'Irish', wiki:'Redbreast_(whiskey)',
   cask:'Ex-Bourbon + Oloroso Sherry Cask (Single Pot Still)',
   house:{nose:'셰리, 말린 과일, 스파이스, 오일리한 몰트', taste:'농밀한 과실과 셰리, 정향, 크리미한 질감', finish:'길고 스파이시한 마무리'}},
  {k:'bushmills', en:'Bushmills', ko:'부시밀', alias:['부쉬밀'], region:'Ireland', country:'아일랜드', type:'Irish', wiki:'Bushmills_Distillery',
   cask:'Ex-Bourbon + Sherry Cask',
   house:{nose:'사과, 바닐라, 꿀', taste:'부드러운 몰트와 과실, 견과', finish:'중간 길이의 마무리'}},
  {k:'teeling', en:'Teeling', ko:'틸링', region:'Ireland', country:'아일랜드', type:'Irish', wiki:'Teeling_Distillery',
   cask:'Ex-Bourbon + Rum Cask',
   house:{nose:'열대 과일, 바닐라, 스파이스', taste:'과실과 럼의 단맛, 스파이스', finish:'중간 길이의 마무리'}},
  {k:'kavalan', en:'Kavalan', ko:'카발란', region:'Taiwan', country:'대만', type:'World Whisky', wiki:'Kavalan_Distillery',
   cask:'Ex-Bourbon + Sherry + Wine Cask',
   house:{nose:'열대 과일, 코코넛, 바닐라, 망고', taste:'농익은 과실과 진한 오크, 단맛', finish:'중간~긴 길이, 달콤한 오크'}},
  {k:'amrut', en:'Amrut', ko:'암룻', region:'India', country:'인도', type:'World Whisky', wiki:'Amrut_distillery',
   cask:'Ex-Bourbon Cask',
   house:{nose:'몰트, 열대 과일, 바닐라', taste:'농축된 몰트와 과실, 스파이스', finish:'중간~긴 길이의 마무리'}},
  {k:'pauljohn', en:'Paul John', ko:'폴존', alias:['폴 존'], region:'India', country:'인도', type:'World Whisky', wiki:'Paul_John_(whisky)',
   cask:'Ex-Bourbon Cask',
   house:{nose:'꿀, 열대 과일, 몰트', taste:'진한 몰트 단맛과 과실, 스파이스', finish:'중간~긴 길이의 마무리'}},
  {k:'mackmyra', en:'Mackmyra', ko:'막미라', region:'Sweden', country:'스웨덴', type:'World Whisky', wiki:'Mackmyra_Whisky',
   cask:'Swedish Oak + Ex-Bourbon',
   house:{nose:'베리, 바닐라, 허브', taste:'가벼운 과실과 몰트, 스파이스', finish:'중간 길이의 마무리'}},
];

/* 제품 라인업 ─ b: 브랜드 키, m: 매칭 토큰, wb: Whiskybase 참고 점수, lo/hi: 국내 추정 시장가 */
const PRODUCTS = [
  {b:'glenfiddich', m:['12'], age:'12', abv:'40', name_en:'Glenfiddich 12 Year Old', wb:'80', lo:60000, hi:80000},
  {b:'glenfiddich', m:['15'], age:'15', abv:'40', name_en:'Glenfiddich 15 Year Old Solera', wb:'84', lo:100000, hi:130000,
   cask:'Solera Vat (Sherry + Bourbon + Virgin Oak)'},
  {b:'glenfiddich', m:['18'], age:'18', abv:'40', name_en:'Glenfiddich 18 Year Old', wb:'86', lo:170000, hi:230000},
  {b:'macallan', m:['12','double','더블'], age:'12', abv:'40', name_en:'The Macallan Double Cask 12 Years Old', wb:'83', lo:140000, hi:190000,
   cask:'American + European Sherry Seasoned Oak'},
  {b:'macallan', m:['12','sherry','셰리'], age:'12', abv:'40', name_en:'The Macallan Sherry Oak 12 Years Old', wb:'86', lo:180000, hi:250000,
   cask:'Sherry Seasoned European Oak'},
  {b:'macallan', m:['18'], age:'18', abv:'43', name_en:'The Macallan 18 Years Old', wb:'89', lo:700000, hi:1100000},
  {b:'glenlivet', m:['12'], age:'12', abv:'40', name_en:'The Glenlivet 12 Year Old', wb:'81', lo:70000, hi:95000},
  {b:'glenlivet', m:['15'], age:'15', abv:'40', name_en:'The Glenlivet 15 Year Old French Oak Reserve', wb:'84', lo:110000, hi:150000,
   cask:'Ex-Bourbon + French Limousin Oak'},
  {b:'balvenie', m:['12','doublewood','더블우드'], age:'12', abv:'40', name_en:'The Balvenie DoubleWood 12 Year Old', wb:'85', lo:110000, hi:150000,
   cask:'Ex-Bourbon → Oloroso Sherry Cask Finish'},
  {b:'balvenie', m:['14','caribbean','캐리비안'], age:'14', abv:'43', name_en:'The Balvenie Caribbean Cask 14 Year Old', wb:'86', lo:150000, hi:200000,
   cask:'Ex-Bourbon → Caribbean Rum Cask Finish'},
  {b:'aberlour', m:['12'], age:'12', abv:'40', name_en:'Aberlour 12 Year Old Double Cask', wb:'84', lo:90000, hi:120000},
  {b:'aberlour', m:['abunadh','아분아','아부나흐','abunadh'], age:'NAS', abv:'60', name_en:"Aberlour A'bunadh (배치 미지정)", wb:'88', lo:150000, hi:210000,
   cask:'First-fill Oloroso Sherry Butt (캐스크 스트렝스)',
   note:'⚠ 배치별 도수(59~61%)가 다릅니다. 보유 배치 라벨 확인 후 수정하세요.'},
  {b:'glenallachie', m:['10','cs','캐스크스트렝스','cask strength'], age:'10', abv:'56', name_en:'GlenAllachie 10 Year Old Cask Strength (배치 미지정)', wb:'87', lo:110000, hi:150000,
   note:'⚠ 배치별 도수(55~58%)와 캐스크 구성이 다릅니다. 보유 배치 라벨 확인 후 수정하세요.'},
  {b:'glenallachie', m:['12'], age:'12', abv:'46', name_en:'GlenAllachie 12 Year Old', wb:'86', lo:100000, hi:135000,
   cask:'PX + Oloroso Sherry + Virgin Oak'},
  {b:'glenallachie', m:['15'], age:'15', abv:'46', name_en:'GlenAllachie 15 Year Old', wb:'87', lo:150000, hi:200000},
  {b:'glenfarclas', m:['105'], age:'NAS', abv:'60', name_en:'Glenfarclas 105 Cask Strength', wb:'86', lo:110000, hi:150000,
   cask:'Oloroso Sherry Cask (캐스크 스트렝스)'},
  {b:'glenfarclas', m:['12'], age:'12', abv:'43', name_en:'Glenfarclas 12 Year Old', wb:'84', lo:80000, hi:110000},
  {b:'ardbeg', m:['10'], age:'10', abv:'46', name_en:'Ardbeg 10 Year Old', wb:'87', lo:85000, hi:110000,
   bible:'97 · Whisky Bible 2008 World Whisky of the Year'},
  {b:'ardbeg', m:['uigeadail','우거달','우가달'], age:'NAS', abv:'54.2', name_en:'Ardbeg Uigeadail', wb:'89', lo:140000, hi:190000,
   cask:'Ex-Bourbon + Oloroso Sherry Cask',
   bible:'97.5 · Whisky Bible 2009 World Whisky of the Year'},
  {b:'ardbeg', m:['corryvreckan','코리브레칸'], age:'NAS', abv:'57.1', name_en:'Ardbeg Corryvreckan', wb:'89', lo:150000, hi:200000,
   cask:'Ex-Bourbon + French Oak'},
  {b:'laphroaig', m:['10'], age:'10', abv:'40', name_en:'Laphroaig 10 Year Old', wb:'85', lo:80000, hi:105000},
  {b:'laphroaig', m:['quarter','쿼터'], age:'NAS', abv:'48', name_en:'Laphroaig Quarter Cask', wb:'87', lo:95000, hi:125000,
   cask:'Ex-Bourbon → Quarter Cask Finish'},
  {b:'lagavulin', m:['16'], age:'16', abv:'43', name_en:'Lagavulin 16 Year Old', wb:'89', lo:150000, hi:200000},
  {b:'lagavulin', m:['8'], age:'8', abv:'48', name_en:'Lagavulin 8 Year Old', wb:'86', lo:100000, hi:135000},
  {b:'bowmore', m:['12'], age:'12', abv:'40', name_en:'Bowmore 12 Year Old', wb:'83', lo:80000, hi:110000},
  {b:'bowmore', m:['15'], age:'15', abv:'43', name_en:'Bowmore 15 Year Old', wb:'86', lo:140000, hi:190000,
   cask:'Ex-Bourbon → Oloroso Sherry Cask Finish'},
  {b:'caolila', m:['12'], age:'12', abv:'43', name_en:'Caol Ila 12 Year Old', wb:'86', lo:100000, hi:135000},
  {b:'talisker', m:['10'], age:'10', abv:'45.8', name_en:'Talisker 10 Year Old', wb:'86', lo:90000, hi:120000},
  {b:'talisker', m:['skye','스카이'], age:'NAS', abv:'45.8', name_en:'Talisker Skye', wb:'82', lo:80000, hi:105000},
  {b:'highlandpark', m:['12'], age:'12', abv:'40', name_en:'Highland Park 12 Year Old Viking Honour', wb:'85', lo:90000, hi:120000},
  {b:'highlandpark', m:['18'], age:'18', abv:'43', name_en:'Highland Park 18 Year Old', wb:'89', lo:300000, hi:420000},
  {b:'glenmorangie', m:['10','original','오리지널'], age:'10', abv:'40', name_en:'Glenmorangie The Original 10 Year Old', wb:'81', lo:65000, hi:90000},
  {b:'glenmorangie', m:['lasanta','라산타'], age:'12', abv:'43', name_en:'Glenmorangie Lasanta 12 Year Old', wb:'83', lo:100000, hi:135000,
   cask:'Ex-Bourbon → Oloroso & PX Sherry Cask Finish'},
  {b:'glenmorangie', m:['quinta','ruban','퀸타','루반'], age:'14', abv:'46', name_en:'Glenmorangie Quinta Ruban 14 Year Old', wb:'85', lo:110000, hi:145000,
   cask:'Ex-Bourbon → Port Pipe Finish'},
  {b:'glenmorangie', m:['nectar','넥타'], age:'12', abv:'46', name_en:"Glenmorangie Nectar d'Or", wb:'84', lo:110000, hi:150000,
   cask:'Ex-Bourbon → Sauternes Cask Finish'},
  {b:'dalmore', m:['12'], age:'12', abv:'40', name_en:'The Dalmore 12 Year Old', wb:'83', lo:110000, hi:150000},
  {b:'dalmore', m:['15'], age:'15', abv:'40', name_en:'The Dalmore 15 Year Old', wb:'86', lo:200000, hi:280000},
  {b:'glendronach', m:['12'], age:'12', abv:'43', name_en:'The GlenDronach 12 Year Old Original', wb:'85', lo:85000, hi:115000},
  {b:'glendronach', m:['15','revival','리바이벌'], age:'15', abv:'46', name_en:'The GlenDronach 15 Year Old Revival', wb:'88', lo:150000, hi:200000},
  {b:'glendronach', m:['18','allardice','알라디스'], age:'18', abv:'46', name_en:'The GlenDronach 18 Year Old Allardice', wb:'89', lo:280000, hi:380000},
  {b:'springbank', m:['10'], age:'10', abv:'46', name_en:'Springbank 10 Year Old', wb:'87', lo:130000, hi:200000},
  {b:'springbank', m:['15'], age:'15', abv:'46', name_en:'Springbank 15 Year Old', wb:'89', lo:250000, hi:400000},
  {b:'oban', m:['14'], age:'14', abv:'43', name_en:'Oban 14 Year Old', wb:'85', lo:110000, hi:150000},
  {b:'clynelish', m:['14'], age:'14', abv:'46', name_en:'Clynelish 14 Year Old', wb:'86', lo:110000, hi:150000},
  {b:'yamazaki', m:['12'], age:'12', abv:'43', name_en:'Suntory Yamazaki 12 Year Old', wb:'86', lo:280000, hi:400000, bible:'≈92',
   note:'국내 시장가 변동이 큰 품목입니다. 시세 확인 후 수정하세요.'},
  {b:'yamazaki', m:['ds','distillers','디스틸러스'], age:'NAS', abv:'43', name_en:"Suntory Yamazaki Distiller's Reserve", wb:'82', lo:150000, hi:230000},
  {b:'hakushu', m:['12'], age:'12', abv:'43', name_en:'Suntory Hakushu 12 Year Old', wb:'86', lo:280000, hi:400000},
  {b:'hibiki', m:['harmony','하모니','하머니'], age:'NAS', abv:'43', name_en:'Suntory Hibiki Japanese Harmony', wb:'84', lo:150000, hi:230000},
  {b:'nikka', m:['barrel','바렐','배럴'], age:'NAS', abv:'51.4', name_en:'Nikka From The Barrel', wb:'86', lo:80000, hi:120000,
   cask:'Ex-Bourbon + Sherry Cask (블렌딩, 캐스크 스트렝스급)'},
  {b:'yoichi', m:['single','nas','요이치'], age:'NAS', abv:'45', name_en:'Nikka Yoichi Single Malt', wb:'85', lo:130000, hi:190000},
  {b:'makersmark', m:['makers','메이커스'], age:'NAS', abv:'45', name_en:"Maker's Mark Kentucky Straight Bourbon", wb:'79', lo:45000, hi:60000, bible:'≈90'},
  {b:'buffalotrace', m:['buffalo','버팔로'], age:'NAS', abv:'45', name_en:'Buffalo Trace Kentucky Straight Bourbon', wb:'82', lo:55000, hi:80000},
  {b:'woodford', m:['double','더블'], age:'NAS', abv:'43.2', name_en:'Woodford Reserve Double Oaked', wb:'84', lo:90000, hi:120000,
   cask:'New Charred American Oak (2차 숙성)'},
  {b:'woodford', m:['woodford','우드포드'], age:'NAS', abv:'43.2', name_en:'Woodford Reserve Distiller\'s Select', wb:'82', lo:65000, hi:90000},
  {b:'wildturkey', m:['101'], age:'NAS', abv:'50.5', name_en:'Wild Turkey 101', wb:'84', lo:50000, hi:70000},
  {b:'wildturkey', m:['rare','breed','레어브리드'], age:'NAS', abv:'58.4', name_en:'Wild Turkey Rare Breed', wb:'87', lo:90000, hi:130000,
   note:'⚠ 배치별 도수가 다릅니다. 라벨 확인 후 수정하세요.'},
  {b:'eaglerare', m:['10'], age:'10', abv:'45', name_en:'Eagle Rare 10 Year Old', wb:'85', lo:90000, hi:140000},
  {b:'blantons', m:['original','오리지널','blantons'], age:'NAS', abv:'46.5', name_en:"Blanton's Original Single Barrel", wb:'86', lo:150000, hi:250000},
  {b:'elijahcraig', m:['small','batch','스몰배치'], age:'NAS', abv:'47', name_en:'Elijah Craig Small Batch', wb:'84', lo:65000, hi:90000},
  {b:'fourroses', m:['small','batch','스몰배치'], age:'NAS', abv:'45', name_en:'Four Roses Small Batch', wb:'83', lo:60000, hi:85000},
  {b:'knobcreek', m:['9'], age:'9', abv:'50', name_en:'Knob Creek 9 Year Old', wb:'84', lo:60000, hi:85000},
  {b:'jameson', m:['jameson','제임슨'], age:'NAS', abv:'40', name_en:'Jameson Irish Whiskey', wb:'77', lo:35000, hi:50000},
  {b:'redbreast', m:['12'], age:'12', abv:'40', name_en:'Redbreast 12 Year Old', wb:'87', lo:110000, hi:150000},
  {b:'johnniewalker', m:['black','블랙'], age:'12', abv:'40', name_en:'Johnnie Walker Black Label 12 Year Old', wb:'82', lo:45000, hi:65000},
  {b:'johnniewalker', m:['green','그린'], age:'15', abv:'43', name_en:'Johnnie Walker Green Label 15 Year Old', wb:'85', lo:80000, hi:110000,
   type:'Blended Malt'},
  {b:'johnniewalker', m:['blue','블루'], age:'NAS', abv:'40', name_en:'Johnnie Walker Blue Label', wb:'86', lo:220000, hi:320000},
  {b:'chivas', m:['12'], age:'12', abv:'40', name_en:'Chivas Regal 12 Year Old', wb:'78', lo:40000, hi:60000},
  {b:'chivas', m:['18'], age:'18', abv:'40', name_en:'Chivas Regal 18 Year Old', wb:'84', lo:110000, hi:150000},
  {b:'monkeyshoulder', m:['monkey','몽키'], age:'NAS', abv:'40', name_en:'Monkey Shoulder Blended Malt', wb:'79', lo:45000, hi:65000},
  {b:'kavalan', m:['classic','클래식'], age:'NAS', abv:'40', name_en:'Kavalan Classic Single Malt', wb:'83', lo:110000, hi:160000},
  {b:'kavalan', m:['solist','솔리스트'], age:'NAS', abv:'57', name_en:'Kavalan Solist (캐스크 미지정)', wb:'88', lo:250000, hi:400000,
   cask:'Single Cask (Sherry / Bourbon / Vinho 등)',
   note:'⚠ 솔리스트는 캐스크 종류·도수가 병마다 다릅니다. 라벨 확인 후 수정하세요.'},
];

/* ── 추가 증류소 ─────────────────────────────────────────────
   house 를 생략하면 REGION_STYLE 의 지역 일반 특성으로 초안을 만든다.
   (근거 없는 개별 테이스팅 노트를 만들지 않기 위한 의도적 설계) */
const BRANDS_MORE = [
  // Speyside
  {k:'longmorn', en:'Longmorn', ko:'롱몬', alias:['롱몬','론몬','longmorn'], region:'Speyside', country:'스코틀랜드', wiki:'Longmorn_distillery', cask:'Ex-Bourbon + Sherry Cask'},
  {k:'glenrothes', en:'The Glenrothes', ko:'글렌로티스', alias:['글렌로세스'], region:'Speyside', country:'스코틀랜드', wiki:'Glenrothes_distillery', cask:'Sherry Seasoned Oak'},
  {k:'aultmore', en:'Aultmore', ko:'올트모어', region:'Speyside', country:'스코틀랜드', wiki:'Aultmore_distillery', cask:'Ex-Bourbon Cask'},
  {k:'miltonduff', en:'Miltonduff', ko:'밀턴더프', region:'Speyside', country:'스코틀랜드', wiki:'Miltonduff_distillery', cask:'Ex-Bourbon Cask'},
  {k:'glenlossie', en:'Glenlossie', ko:'글렌로시', region:'Speyside', country:'스코틀랜드', wiki:'Glenlossie_distillery', cask:'Ex-Bourbon Cask'},
  {k:'inchgower', en:'Inchgower', ko:'인치가워', region:'Speyside', country:'스코틀랜드', wiki:'Inchgower_distillery', cask:'Ex-Bourbon Cask'},
  {k:'auchroisk', en:'Auchroisk', ko:'오크로이스크', region:'Speyside', country:'스코틀랜드', wiki:'Auchroisk_distillery', cask:'Ex-Bourbon Cask'},
  {k:'glenelgin', en:'Glen Elgin', ko:'글렌엘긴', region:'Speyside', country:'스코틀랜드', wiki:'Glen_Elgin_distillery', cask:'Ex-Bourbon + Sherry Cask'},
  {k:'dailuaine', en:'Dailuaine', ko:'다일유안', alias:['달유아인'], region:'Speyside', country:'스코틀랜드', wiki:'Dailuaine_distillery', cask:'Sherry Cask'},
  {k:'knockando', en:'Knockando', ko:'녹칸두', region:'Speyside', country:'스코틀랜드', wiki:'Knockando_distillery', cask:'Ex-Bourbon + Sherry Cask'},
  {k:'tomintoul', en:'Tomintoul', ko:'토민토울', region:'Speyside', country:'스코틀랜드', wiki:'Tomintoul_distillery', cask:'Ex-Bourbon Cask'},
  {k:'balmenach', en:'Balmenach', ko:'발메낙', region:'Speyside', country:'스코틀랜드', wiki:'Balmenach_distillery', cask:'Ex-Bourbon + Sherry Cask'},
  {k:'tormore', en:'Tormore', ko:'토모어', region:'Speyside', country:'스코틀랜드', wiki:'Tormore_distillery', cask:'Ex-Bourbon Cask'},
  {k:'dufftown', en:'Dufftown', ko:'더프타운', region:'Speyside', country:'스코틀랜드', wiki:'Dufftown_distillery', cask:'Ex-Bourbon Cask'},
  {k:'glentauchers', en:'Glentauchers', ko:'글렌토커스', region:'Speyside', country:'스코틀랜드', wiki:'Glentauchers_distillery', cask:'Ex-Bourbon Cask'},
  {k:'mannochmore', en:'Mannochmore', ko:'만녹모어', region:'Speyside', country:'스코틀랜드', wiki:'Mannochmore_distillery', cask:'Ex-Bourbon Cask'},
  {k:'braeval', en:'Braeval', ko:'브레이발', region:'Speyside', country:'스코틀랜드', wiki:'Braeval_distillery', cask:'Ex-Bourbon Cask'},
  // Highland
  {k:'bennevis', en:'Ben Nevis', ko:'벤네비스', alias:['벤 네비스'], region:'Highland', country:'스코틀랜드', wiki:'Ben_Nevis_distillery', cask:'Ex-Bourbon + Sherry Cask'},
  {k:'blairathol', en:'Blair Athol', ko:'블레어아솔', region:'Highland', country:'스코틀랜드', wiki:'Blair_Athol_distillery', cask:'Sherry Cask'},
  {k:'fettercairn', en:'Fettercairn', ko:'페터케런', alias:['페터케언'], region:'Highland', country:'스코틀랜드', wiki:'Fettercairn_distillery', cask:'Ex-Bourbon Cask'},
  {k:'glencadam', en:'Glencadam', ko:'글렌카담', region:'Highland', country:'스코틀랜드', wiki:'Glencadam_distillery', cask:'Ex-Bourbon Cask'},
  {k:'royallochnagar', en:'Royal Lochnagar', ko:'로열로크나가', alias:['로얄로크나가'], region:'Highland', country:'스코틀랜드', wiki:'Royal_Lochnagar_distillery', cask:'Ex-Bourbon + Sherry Cask'},
  {k:'teaninich', en:'Teaninich', ko:'티니닉', region:'Highland', country:'스코틀랜드', wiki:'Teaninich_distillery', cask:'Ex-Bourbon Cask'},
  {k:'tullibardine', en:'Tullibardine', ko:'툴리바딘', region:'Highland', country:'스코틀랜드', wiki:'Tullibardine_distillery', cask:'Ex-Bourbon + Wine Cask Finish'},
  {k:'glenord', en:'Glen Ord', ko:'글렌오드', alias:['싱글톤 글렌오드'], region:'Highland', country:'스코틀랜드', wiki:'Glen_Ord_distillery', cask:'Ex-Bourbon + Sherry Cask'},
  {k:'ardmore', en:'Ardmore', ko:'아드모어', region:'Highland', country:'스코틀랜드', wiki:'Ardmore_distillery', cask:'Ex-Bourbon Cask (피티드)'},
  {k:'glengarioch', en:'Glen Garioch', ko:'글렌기리', alias:['글렌개리오크'], region:'Highland', country:'스코틀랜드', wiki:'Glen_Garioch_distillery', cask:'Ex-Bourbon + Sherry Cask'},
  {k:'ancnoc', en:'anCnoc (Knockdhu)', ko:'아녹', alias:['안녹','녹두'], region:'Highland', country:'스코틀랜드', wiki:'Knockdhu_distillery', cask:'Ex-Bourbon + Sherry Cask'},
  {k:'glenturret', en:'The Glenturret', ko:'글렌터렛', region:'Highland', country:'스코틀랜드', wiki:'Glenturret_distillery', cask:'Ex-Bourbon + Sherry Cask'},
  {k:'wolfburn', en:'Wolfburn', ko:'울프번', region:'Highland', country:'스코틀랜드', wiki:'Wolfburn_distillery', cask:'Ex-Bourbon Cask'},
  {k:'ardnamurchan', en:'Ardnamurchan', ko:'아드나머칸', region:'Highland', country:'스코틀랜드', wiki:'Ardnamurchan_distillery', cask:'Ex-Bourbon + Sherry Cask'},
  // Island / Islay / Campbeltown / Lowland
  {k:'ledaig', en:'Ledaig (Tobermory)', ko:'레댁', alias:['레이딕','토버모리','tobermory'], region:'Island', country:'스코틀랜드', wiki:'Tobermory_distillery', cask:'Ex-Bourbon + Sherry Cask (피티드)'},
  {k:'scapa', en:'Scapa', ko:'스카파', region:'Island', country:'스코틀랜드', wiki:'Scapa_distillery', cask:'Ex-Bourbon Cask'},
  {k:'raasay', en:'Isle of Raasay', ko:'라세이', alias:['아일오브라세이'], region:'Island', country:'스코틀랜드', wiki:'Isle_of_Raasay_distillery', cask:'Ex-Bourbon + Rye + Wine Cask'},
  {k:'portcharlotte', en:'Port Charlotte (Bruichladdich)', ko:'포트샬롯', alias:['포트 샬롯'], region:'Islay', country:'스코틀랜드', wiki:'Bruichladdich_distillery', cask:'Ex-Bourbon + Wine Cask (피티드)'},
  {k:'octomore', en:'Octomore (Bruichladdich)', ko:'옥토모어', region:'Islay', country:'스코틀랜드', wiki:'Bruichladdich_distillery', cask:'Ex-Bourbon + Wine Cask (초강피트)'},
  {k:'ardnahoe', en:'Ardnahoe', ko:'아드나호', region:'Islay', country:'스코틀랜드', wiki:'Ardnahoe_distillery', cask:'Ex-Bourbon + Sherry Cask (피티드)'},
  {k:'kilkerran', en:'Kilkerran (Glengyle)', ko:'킬커란', alias:['글렌가일'], region:'Campbeltown', country:'스코틀랜드', wiki:'Glengyle_distillery', cask:'Ex-Bourbon + Sherry Cask'},
  {k:'longrow', en:'Longrow (Springbank)', ko:'롱로우', region:'Campbeltown', country:'스코틀랜드', wiki:'Springbank_distillery', cask:'Ex-Bourbon + Sherry Cask (피티드)'},
  {k:'hazelburn', en:'Hazelburn (Springbank)', ko:'헤이즐번', region:'Campbeltown', country:'스코틀랜드', wiki:'Springbank_distillery', cask:'Ex-Bourbon Cask (3회 증류)'},
  {k:'bladnoch', en:'Bladnoch', ko:'블라드녹', region:'Lowland', country:'스코틀랜드', wiki:'Bladnoch_distillery', cask:'Ex-Bourbon + Sherry Cask'},
  {k:'ailsabay', en:'Ailsa Bay', ko:'아일사베이', region:'Lowland', country:'스코틀랜드', wiki:'Ailsa_Bay_distillery', cask:'Ex-Bourbon Cask (피티드)'},
  {k:'daftmill', en:'Daftmill', ko:'다프트밀', region:'Lowland', country:'스코틀랜드', wiki:'Daftmill_distillery', cask:'Ex-Bourbon + Sherry Cask'},
  {k:'kingsbarns', en:'Kingsbarns', ko:'킹스반스', region:'Lowland', country:'스코틀랜드', wiki:'Kingsbarns_distillery', cask:'Ex-Bourbon Cask'},
  // Japan
  {k:'mars', en:'Mars Shinshu', ko:'마스신슈', alias:['마르스','신슈'], region:'Japan', country:'일본', type:'Japanese Single Malt', wiki:'Mars_Shinshu_distillery', cask:'Ex-Bourbon + Sherry Cask'},
  {k:'fuji', en:'Fuji Gotemba', ko:'후지고템바', alias:['후지산로쿠','fuji'], region:'Japan', country:'일본', type:'Japanese Blended', wiki:'Fuji_Gotemba_Distillery', cask:'Ex-Bourbon Cask'},
  {k:'akkeshi', en:'Akkeshi', ko:'아케시', region:'Japan', country:'일본', type:'Japanese Single Malt', wiki:'Akkeshi_distillery', cask:'Ex-Bourbon + Mizunara'},
  {k:'kanosuke', en:'Kanosuke', ko:'카노스케', alias:['가노스케'], region:'Japan', country:'일본', type:'Japanese Single Malt', wiki:'Kanosuke_Distillery', cask:'Ex-Bourbon + Sherry Cask'},
  {k:'taketsuru', en:'Nikka Taketsuru', ko:'타케츠루', alias:['다케쓰루'], region:'Japan', country:'일본', type:'Blended Malt', wiki:'Nikka_Whisky_Distilling', cask:'Ex-Bourbon + Sherry Cask (블렌딩)'},
  // USA
  {k:'oldforester', en:'Old Forester', ko:'올드포레스터', region:'Kentucky', country:'미국', type:'Bourbon', wiki:'Old_Forester', cask:'New Charred American Oak'},
  {k:'weller', en:'W. L. Weller', ko:'웰러', alias:['웰러','wl weller'], region:'Kentucky', country:'미국', type:'Bourbon', wiki:'W._L._Weller', cask:'New Charred American Oak (휘티드)'},
  {k:'bookers', en:"Booker's", ko:'부커스', region:'Kentucky', country:'미국', type:'Bourbon', wiki:"Booker's_Bourbon", cask:'New Charred American Oak (캐스크 스트렝스)'},
  {k:'basilhayden', en:'Basil Hayden', ko:'바질헤이든', region:'Kentucky', country:'미국', type:'Bourbon', wiki:'Basil_Hayden%27s', cask:'New Charred American Oak (하이 라이)'},
  {k:'russells', en:"Russell's Reserve", ko:'러셀스리저브', alias:['러셀 리저브'], region:'Kentucky', country:'미국', type:'Bourbon', wiki:'Wild_Turkey_(bourbon)', cask:'New Charred American Oak'},
  {k:'angelsenvy', en:"Angel's Envy", ko:'엔젤스엔비', region:'Kentucky', country:'미국', type:'Bourbon', wiki:"Angel's_Envy", cask:'New Charred Oak → Port Cask Finish'},
  {k:'larceny', en:'Larceny', ko:'라세니', region:'Kentucky', country:'미국', type:'Bourbon', wiki:'Heaven_Hill', cask:'New Charred American Oak (휘티드)'},
  {k:'rittenhouse', en:'Rittenhouse Rye', ko:'리튼하우스', region:'Kentucky', country:'미국', type:'Rye', wiki:'Heaven_Hill', cask:'New Charred American Oak'},
  {k:'bulleit', en:'Bulleit', ko:'불렛', alias:['불릿'], region:'Kentucky', country:'미국', type:'Bourbon', wiki:'Bulleit_Bourbon', cask:'New Charred American Oak (하이 라이)'},
  {k:'ehtaylor', en:'Colonel E.H. Taylor', ko:'이에이치테일러', alias:['eh taylor','테일러'], region:'Kentucky', country:'미국', type:'Bourbon', wiki:'Buffalo_Trace_Distillery', cask:'New Charred American Oak'},
  // Ireland / World
  {k:'greenspot', en:'Green Spot', ko:'그린스팟', region:'Ireland', country:'아일랜드', type:'Irish', wiki:'Green_Spot_(whiskey)', cask:'Ex-Bourbon + Sherry Cask (Single Pot Still)'},
  {k:'yellowspot', en:'Yellow Spot', ko:'옐로스팟', alias:['옐로우스팟'], region:'Ireland', country:'아일랜드', type:'Irish', wiki:'Yellow_Spot_(whiskey)', cask:'Ex-Bourbon + Sherry + Malaga Cask'},
  {k:'powers', en:'Powers', ko:'파워스', region:'Ireland', country:'아일랜드', type:'Irish', wiki:'Powers_(whiskey)', cask:'Ex-Bourbon Cask (Single Pot Still)'},
  {k:'connemara', en:'Connemara', ko:'코네마라', region:'Ireland', country:'아일랜드', type:'Irish', wiki:'Cooley_Distillery', cask:'Ex-Bourbon Cask (피티드)'},
  {k:'writerstears', en:"Writers' Tears", ko:'라이터스티어스', alias:['작가의눈물'], region:'Ireland', country:'아일랜드', type:'Irish', wiki:'Walsh_Whiskey_Distillery', cask:'Ex-Bourbon Cask (블렌딩)'},
  {k:'starward', en:'Starward', ko:'스타워드', region:'Australia', country:'호주', type:'World Whisky', wiki:'Starward_Whisky', cask:'Australian Red Wine Barrel'},
  {k:'sullivans', en:'Sullivans Cove', ko:'설리번스코브', region:'Australia', country:'호주', type:'World Whisky', wiki:'Sullivans_Cove_whisky', cask:'Ex-Bourbon + French Oak'},
  {k:'omar', en:'Omar (Nantou)', ko:'오마', alias:['난터우'], region:'Taiwan', country:'대만', type:'World Whisky', wiki:'Nantou_Distillery', cask:'Ex-Bourbon + Sherry + Fruit Wine Cask'},
  {k:'milkhoney', en:'Milk & Honey', ko:'밀크앤허니', alias:['m&h'], region:'Israel', country:'이스라엘', type:'World Whisky', wiki:'Milk_%26_Honey_Distillery', cask:'Ex-Bourbon + Wine Cask'},
  {k:'penderyn', en:'Penderyn', ko:'펜더린', region:'Wales', country:'웨일스', type:'World Whisky', wiki:'Penderyn_distillery', cask:'Ex-Bourbon + Madeira Cask'},
  {k:'armorik', en:'Armorik', ko:'아르모릭', region:'France', country:'프랑스', type:'World Whisky', wiki:'Warenghem_distillery', cask:'Ex-Bourbon + Sherry Cask'},
];
BRANDS.push(...BRANDS_MORE);

/* 독립 병입자(IB) — 감지되면 보틀러 필드와 주의 문구를 채운다 */
const BOTTLERS = [
  {en:'Signatory Vintage', ko:'시그나토리', alias:['시그네토리','signatory']},
  {en:'Gordon & MacPhail', ko:'고든앤맥페일', alias:['고든 앤 맥페일','g&m','gordon macphail']},
  {en:"Wm Cadenhead", ko:'카데나스', alias:['카데헤드','cadenhead']},
  {en:'Douglas Laing', ko:'더글라스랭', alias:['올드파티큘러','old particular','provenance','scallywag','big peat']},
  {en:'Hunter Laing', ko:'헌터랭', alias:['올드몰트캐스크','old malt cask']},
  {en:'Elixir Distillers', ko:'엘릭서', alias:['싱글몰트오브스코틀랜드','single malts of scotland']},
  {en:'Berry Bros & Rudd', ko:'베리브로스', alias:['berry bros']},
  {en:"That Boutique-y Whisky Company", ko:'부티키', alias:['boutique-y','부티크']},
  {en:'Wilson & Morgan', ko:'윌슨앤모건', alias:['wilson morgan']},
];

/* ── 대량 증류소 목록 ────────────────────────────────────────
   앱이 한글↔영문을 발음 골격으로 매칭하므로 한글 별칭이 없어도 검색된다.
   형식: [영문명, 지역, (국가), (타입), (비고)] */
const REGION_CASK = {
  Islay:'Ex-Bourbon Barrel (피티드)', Speyside:'Ex-Bourbon + Sherry Cask',
  Highland:'Ex-Bourbon + Sherry Cask', Island:'Ex-Bourbon + Sherry Cask',
  Lowland:'Ex-Bourbon Cask', Campbeltown:'Ex-Bourbon + Sherry Cask',
  Kentucky:'New Charred American Oak', Tennessee:'New Charred American Oak (숯 여과)',
  Japan:'Ex-Bourbon + Sherry Cask', Ireland:'Ex-Bourbon + Sherry Cask',
  Blend:'Ex-Bourbon + Sherry Cask (블렌딩)', _:'Ex-Bourbon Cask',
};
const REGION_TYPE = {
  Kentucky:'Bourbon', Tennessee:'Tennessee Whiskey', Japan:'Japanese Single Malt',
  Ireland:'Irish', Blend:'Blended Scotch',
};
const REGION_COUNTRY = {
  Islay:'스코틀랜드', Speyside:'스코틀랜드', Highland:'스코틀랜드', Island:'스코틀랜드',
  Lowland:'스코틀랜드', Campbeltown:'스코틀랜드', Blend:'스코틀랜드',
  Kentucky:'미국', Tennessee:'미국', Japan:'일본', Ireland:'아일랜드',
};
const BRANDS_COMPACT = [
  // ── Speyside
  ['Cardhu','Speyside'], ['Benrinnes','Speyside'], ['Strathmill','Speyside'],
  ['Glen Spey','Speyside'], ['Glenburgie','Speyside'], ['Glen Keith','Speyside'],
  ['Allt-a-Bhainne','Speyside'], ['Kininvie','Speyside'], ['Roseisle','Speyside'],
  ['Caperdonich','Speyside',null,null,'폐쇄 증류소 — 유통 물량은 대부분 독립 병입입니다.'],
  ['Convalmore','Speyside',null,null,'폐쇄 증류소'],
  ['Dallas Dhu','Speyside',null,null,'폐쇄 증류소'],
  ['Pittyvaich','Speyside',null,null,'폐쇄 증류소'],
  ['Coleburn','Speyside',null,null,'폐쇄 증류소'],
  ['Imperial','Speyside',null,null,'폐쇄 증류소'],
  // ── Highland
  ['Royal Brackla','Highland'], ['Glenglassaugh','Highland'], ['Macduff','Highland'],
  ['Nc\'nean','Highland'], ['GlenWyvis','Highland'], ['Dornoch','Highland'],
  ['Brora','Highland',null,null,'폐쇄 후 2021년 재가동 — 구 병입은 고가입니다.'],
  ['Glenugie','Highland',null,null,'폐쇄 증류소'],
  ['Glenlochy','Highland',null,null,'폐쇄 증류소'],
  ['Millburn','Highland',null,null,'폐쇄 증류소'],
  // ── Islay / Island
  ['Port Ellen','Islay',null,null,'폐쇄 후 2024년 재가동 — 구 병입은 고가입니다.'],
  ['Lagg','Island'], ['Abhainn Dearg','Island'],
  // ── Lowland
  ['Rosebank','Lowland'], ['Littlemill','Lowland',null,null,'폐쇄 증류소'],
  ['Clydeside','Lowland'], ['Lindores Abbey','Lowland'], ['Holyrood','Lowland'],
  ['Annandale','Lowland'], ['InchDairnie','Lowland'], ['The Borders','Lowland'],
  ['Lochlea','Lowland'],
  // ── Japan
  ['Karuizawa','Japan',null,null,'폐쇄 증류소 — 경매 위주로 거래됩니다.'],
  ['Shizuoka','Japan'], ['Saburomaru','Japan'], ['Nagahama','Japan'],
  ['Eigashima','Japan'], ['Yuza','Japan'], ['Matsui','Japan'], ['Togouchi','Japan'],
  ["Ichiro's Malt",'Japan'],
  // ── USA
  ['Jim Beam','Kentucky'], ['Evan Williams','Kentucky'], ['Heaven Hill','Kentucky'],
  ['1792','Kentucky'], ['Old Grand-Dad','Kentucky'], ['Willett','Kentucky'],
  ['Old Fitzgerald','Kentucky'], ['Yellowstone','Kentucky'], ['New Riff','Kentucky'],
  ['George T. Stagg','Kentucky'], ['High West','미국','미국','Bourbon'],
  ['WhistlePig','미국','미국','Rye'], ['Balcones','미국','미국','World Whisky'],
  ['Westward','미국','미국','World Whisky'], ['Uncle Nearest','Tennessee'],
  // ── Ireland
  ['Midleton','Ireland'], ['Tullamore D.E.W.','Ireland'], ['Roe & Co','Ireland'],
  ['Dingle','Ireland'], ['Waterford','Ireland'], ['Slane','Ireland'],
  ['Glendalough','Ireland'], ['Knappogue Castle','Ireland'], ['West Cork','Ireland'],
  ['Method and Madness','Ireland'],
  // ── World
  ['Rampur','인도','인도','World Whisky'], ['Indri','인도','인도','World Whisky'],
  ['Bimber','잉글랜드','영국','World Whisky'], ['Cotswolds','잉글랜드','영국','World Whisky'],
  ['The Lakes','잉글랜드','영국','World Whisky'], ['Lark','태즈메이니아','호주','World Whisky'],
  ['Hellyers Road','태즈메이니아','호주','World Whisky'], ['Slyrs','독일','독일','World Whisky'],
  ['Puni','이탈리아','이탈리아','World Whisky'], ['Millstone','네덜란드','네덜란드','World Whisky'],
  ['Stauning','덴마크','덴마크','World Whisky'], ['High Coast','스웨덴','스웨덴','World Whisky'],
  ['Teerenpeli','핀란드','핀란드','World Whisky'], ['Kyrö','핀란드','핀란드','World Whisky'],
  // ── Blended Scotch
  ["Grant's",'Blend'], ["Dewar's",'Blend'], ["Buchanan's",'Blend'], ['Old Parr','Blend'],
  ['White Horse','Blend'], ["Teacher's",'Blend'], ['Cutty Sark','Blend'], ['J&B','Blend'],
  ['Whyte & Mackay','Blend'], ['Naked Malt','Blend',null,'Blended Malt'],
  ['Royal Salute','Blend'], ['Copper Dog','Blend',null,'Blended Malt'],
  ['Islay Mist','Blend'], ['Hankey Bannister','Blend'], ["William Lawson's",'Blend'],
  ['Passport','Blend'],
];
{
  const seen = new Set(BRANDS.map(b => b.k));
  for (const [en, region, country, type, note] of BRANDS_COMPACT){
    const k = en.toLowerCase().replace(/[^a-z0-9]/g, '');
    if (!k || seen.has(k)) continue;
    seen.add(k);
    BRANDS.push({
      k, en, ko:'', region,
      country: country || REGION_COUNTRY[region] || '스코틀랜드',
      type: type || REGION_TYPE[region] || 'Single Malt',
      cask: REGION_CASK[region] || REGION_CASK._,
      wiki: en.replace(/[^\w\s'-]/g, '').trim().replace(/\s+/g, '_') +
        (REGION_COUNTRY[region] === '스코틀랜드' && region !== 'Blend' ? '_distillery' : ''),
      note,
    });
  }
}

/* ── 제품 라인업 2차 확충 ────────────────────────────────────
   국내 유통량이 많은 표현 위주. lo/hi 는 국내 추정 시장가(원)이며 참고값이다. */
const PRODUCTS_MORE = [
  // ── American
  {b:'larceny', m:['barrel proof','배럴프루프','바렐프루프','바프'], age:'NAS', abv:'61',
   name_en:'Larceny Barrel Proof (배치 미지정)', wb:'86', lo:110000, hi:160000,
   cask:'New Charred American Oak (휘티드, 캐스크 스트렝스)',
   note:'⚠ 배치(A/B/C + 연도)마다 도수가 60~62%로 다릅니다. 라벨의 배치 코드를 확인해 수정하세요.'},
  {b:'larceny', m:['small batch','스몰배치','라세니'], age:'NAS', abv:'46',
   name_en:'Larceny Small Batch', wb:'80', lo:50000, hi:70000},
  {b:'elijahcraig', m:['barrel proof','배럴프루프','바렐프루프'], age:'12', abv:'62',
   name_en:'Elijah Craig Barrel Proof (배치 미지정)', wb:'89', lo:150000, hi:230000,
   cask:'New Charred American Oak (캐스크 스트렝스)',
   note:'⚠ 배치별 도수 60~68%. 라벨 배치 코드 확인 후 수정하세요.'},
  {b:'elijahcraig', m:['18'], age:'18', abv:'45', name_en:'Elijah Craig 18 Year Old Single Barrel', wb:'88', lo:400000, hi:600000},
  {b:'weller', m:['special reserve','스페셜리저브'], age:'NAS', abv:'45', name_en:'W. L. Weller Special Reserve', wb:'82', lo:90000, hi:150000},
  {b:'weller', m:['antique','앤티크','107'], age:'NAS', abv:'53.5', name_en:'W. L. Weller Antique 107', wb:'86', lo:150000, hi:250000},
  {b:'weller', m:['12'], age:'12', abv:'45', name_en:'W. L. Weller 12 Year Old', wb:'87', lo:200000, hi:350000},
  {b:'bookers', m:['bookers','부커스'], age:'NAS', abv:'62.5', name_en:"Booker's Small Batch (배치 미지정)", wb:'87', lo:150000, hi:230000,
   note:'⚠ 배치별 도수·숙성이 다릅니다(보통 6~7년, 61~64%).'},
  {b:'russells', m:['10'], age:'10', abv:'45', name_en:"Russell's Reserve 10 Year Old", wb:'84', lo:75000, hi:110000},
  {b:'russells', m:['single barrel','싱글배럴'], age:'NAS', abv:'55', name_en:"Russell's Reserve Single Barrel", wb:'87', lo:130000, hi:200000},
  {b:'ehtaylor', m:['small batch','스몰배치'], age:'NAS', abv:'50', name_en:'Colonel E.H. Taylor Small Batch', wb:'86', lo:150000, hi:250000,
   cask:'New Charred American Oak (Bottled in Bond)'},
  {b:'georgetstagg', m:['stagg','스태그'], age:'NAS', abv:'65', name_en:'Stagg (배치 미지정)', wb:'88', lo:180000, hi:280000,
   cask:'New Charred American Oak (캐스크 스트렝스)', note:'⚠ 배치별 도수 63~68%.'},
  {b:'oldforester', m:['1920'], age:'NAS', abv:'57.5', name_en:'Old Forester 1920 Prohibition Style', wb:'87', lo:110000, hi:160000},
  {b:'oldforester', m:['100','signature'], age:'NAS', abv:'50', name_en:'Old Forester 100 Proof', wb:'83', lo:60000, hi:85000},
  {b:'michters', m:['us1','us*1','바닐라'], age:'NAS', abv:'45.7', name_en:"Michter's US*1 Small Batch Bourbon", wb:'84', lo:100000, hi:150000},
  {b:'jackdaniels', m:['single barrel','싱글배럴'], age:'NAS', abv:'47', name_en:"Jack Daniel's Single Barrel Select", wb:'82', lo:80000, hi:120000},
  {b:'jackdaniels', m:['old no 7','올드7','블랙라벨'], age:'NAS', abv:'40', name_en:"Jack Daniel's Old No.7", wb:'75', lo:35000, hi:50000},
  {b:'wildturkey', m:['8'], age:'8', abv:'50.5', name_en:'Wild Turkey 8 Year Old 101', wb:'85', lo:70000, hi:95000},
  {b:'fourroses', m:['single barrel','싱글배럴'], age:'NAS', abv:'50', name_en:'Four Roses Single Barrel', wb:'86', lo:90000, hi:130000},
  {b:'bulleit', m:['bourbon','버번'], age:'NAS', abv:'45', name_en:'Bulleit Bourbon', wb:'80', lo:50000, hi:70000},
  {b:'bulleit', m:['rye','라이'], age:'NAS', abv:'45', name_en:'Bulleit Rye', wb:'83', lo:55000, hi:75000, type:'Rye'},
  {b:'knobcreek', m:['12'], age:'12', abv:'50', name_en:'Knob Creek 12 Year Old', wb:'87', lo:100000, hi:150000},
  {b:'jimbeam', m:['black','블랙'], age:'NAS', abv:'43', name_en:'Jim Beam Black Extra Aged', wb:'80', lo:45000, hi:65000},
  {b:'evanwilliams', m:['black','블랙','1783'], age:'NAS', abv:'43', name_en:'Evan Williams Black Label', wb:'78', lo:35000, hi:50000},
  {b:'whistlepig', m:['10'], age:'10', abv:'50', name_en:'WhistlePig 10 Year Old Rye', wb:'87', lo:150000, hi:220000, type:'Rye'},
  {b:'highwest', m:['double rye','더블라이'], age:'NAS', abv:'46', name_en:'High West Double Rye!', wb:'84', lo:90000, hi:130000, type:'Rye'},
  {b:'balcones', m:['baby blue','베이비블루'], age:'NAS', abv:'46', name_en:'Balcones Baby Blue', wb:'84', lo:110000, hi:160000},
  // ── Scotch: Speyside / Highland
  {b:'macallan', m:['15','double'], age:'15', abv:'43', name_en:'The Macallan Double Cask 15 Years Old', wb:'86', lo:300000, hi:450000},
  {b:'macallan', m:['triple','트리플'], age:'12', abv:'40', name_en:'The Macallan Triple Cask Matured 12 Years Old', wb:'83', lo:150000, hi:220000},
  {b:'glenlivet', m:['18'], age:'18', abv:'40', name_en:'The Glenlivet 18 Year Old', wb:'87', lo:220000, hi:330000},
  {b:'glenlivet', m:['founders','파운더스'], age:'NAS', abv:'40', name_en:"The Glenlivet Founder's Reserve", wb:'78', lo:55000, hi:80000},
  {b:'balvenie', m:['21','portwood','포트우드'], age:'21', abv:'40', name_en:'The Balvenie PortWood 21 Year Old', wb:'89', lo:600000, hi:900000},
  {b:'balvenie', m:['16','french','프렌치'], age:'16', abv:'47.6', name_en:'The Balvenie French Oak 16 Year Old', wb:'86', lo:250000, hi:350000},
  {b:'aberlour', m:['16'], age:'16', abv:'43', name_en:'Aberlour 16 Year Old Double Cask', wb:'86', lo:150000, hi:220000},
  {b:'aberlour', m:['14'], age:'14', abv:'40', name_en:'Aberlour 14 Year Old Double Cask', wb:'84', lo:100000, hi:140000},
  {b:'glenfiddich', m:['21','reserva','그랑레제르바'], age:'21', abv:'40', name_en:'Glenfiddich 21 Year Old Gran Reserva', wb:'88', lo:450000, hi:650000},
  {b:'glenfiddich', m:['14','bourbon','버번배럴'], age:'14', abv:'43', name_en:'Glenfiddich 14 Year Old Bourbon Barrel', wb:'83', lo:100000, hi:140000},
  {b:'glenallachie', m:['18'], age:'18', abv:'46', name_en:'GlenAllachie 18 Year Old', wb:'89', lo:300000, hi:450000},
  {b:'glenallachie', m:['8'], age:'8', abv:'46', name_en:'GlenAllachie 8 Year Old', wb:'85', lo:85000, hi:120000},
  {b:'glenfarclas', m:['15'], age:'15', abv:'46', name_en:'Glenfarclas 15 Year Old', wb:'88', lo:150000, hi:220000},
  {b:'glenfarclas', m:['21'], age:'21', abv:'43', name_en:'Glenfarclas 21 Year Old', wb:'89', lo:300000, hi:450000},
  {b:'glendronach', m:['21','파클라스','parliament','팔러먼트'], age:'21', abv:'48', name_en:'The GlenDronach Parliament 21 Year Old', wb:'90', lo:400000, hi:600000},
  {b:'glenmorangie', m:['18'], age:'18', abv:'43', name_en:'Glenmorangie 18 Year Old Extremely Rare', wb:'87', lo:250000, hi:360000},
  {b:'glenmorangie', m:['signet','시그넷'], age:'NAS', abv:'46', name_en:'Glenmorangie Signet', wb:'89', lo:300000, hi:450000,
   cask:'Chocolate Malt + Ex-Bourbon + Sherry Cask'},
  {b:'dalmore', m:['18'], age:'18', abv:'43', name_en:'The Dalmore 18 Year Old', wb:'88', lo:450000, hi:650000},
  {b:'dalmore', m:['cigar','시가몰트'], age:'NAS', abv:'44', name_en:'The Dalmore Cigar Malt Reserve', wb:'87', lo:250000, hi:380000},
  {b:'aberfeldy', m:['12'], age:'12', abv:'40', name_en:'Aberfeldy 12 Year Old', wb:'83', lo:70000, hi:100000},
  {b:'aberfeldy', m:['16'], age:'16', abv:'40', name_en:'Aberfeldy 16 Year Old', wb:'86', lo:150000, hi:220000},
  {b:'craigellachie', m:['13'], age:'13', abv:'46', name_en:'Craigellachie 13 Year Old', wb:'86', lo:100000, hi:150000},
  {b:'benriach', m:['10','smoky','스모키'], age:'10', abv:'46', name_en:'BenRiach The Smoky Ten', wb:'85', lo:80000, hi:115000},
  {b:'benriach', m:['12','original','오리지널'], age:'12', abv:'46', name_en:'BenRiach The Twelve', wb:'86', lo:100000, hi:145000},
  {b:'tamdhu', m:['15'], age:'15', abv:'46', name_en:'Tamdhu 15 Year Old', wb:'87', lo:180000, hi:260000},
  {b:'mortlach', m:['16','distillers','디스틸러스'], age:'16', abv:'43.4', name_en:"Mortlach 16 Year Old Distiller's Dram", wb:'87', lo:200000, hi:290000},
  {b:'benromach', m:['10'], age:'10', abv:'43', name_en:'Benromach 10 Year Old', wb:'86', lo:90000, hi:130000},
  {b:'glenrothes', m:['12'], age:'12', abv:'40', name_en:'The Glenrothes 12 Year Old', wb:'84', lo:100000, hi:145000},
  {b:'oldpulteney', m:['12'], age:'12', abv:'40', name_en:'Old Pulteney 12 Year Old', wb:'83', lo:75000, hi:105000},
  {b:'glengoyne', m:['12'], age:'12', abv:'43', name_en:'Glengoyne 12 Year Old', wb:'84', lo:90000, hi:130000},
  {b:'tomatin', m:['12'], age:'12', abv:'43', name_en:'Tomatin 12 Year Old', wb:'82', lo:60000, hi:90000},
  {b:'ancnoc', m:['12'], age:'12', abv:'40', name_en:'anCnoc 12 Year Old', wb:'84', lo:75000, hi:110000},
  {b:'bennevis', m:['10'], age:'10', abv:'46', name_en:'Ben Nevis 10 Year Old', wb:'87', lo:110000, hi:160000},
  // ── Scotch: Islay / Island / Campbeltown
  {b:'ardbeg', m:['an oa','안오','아노아'], age:'NAS', abv:'46.6', name_en:'Ardbeg An Oa', wb:'86', lo:110000, hi:155000,
   cask:'PX Sherry + Virgin Oak + Ex-Bourbon'},
  {b:'ardbeg', m:['wee beastie','위비스티','5'], age:'5', abv:'47.4', name_en:'Ardbeg Wee Beastie', wb:'85', lo:80000, hi:115000},
  {b:'laphroaig', m:['lore','로어'], age:'NAS', abv:'48', name_en:'Laphroaig Lore', wb:'87', lo:150000, hi:220000},
  {b:'laphroaig', m:['triple wood','트리플우드'], age:'NAS', abv:'48', name_en:'Laphroaig Triple Wood', wb:'87', lo:120000, hi:170000},
  {b:'laphroaig', m:['15'], age:'15', abv:'43', name_en:'Laphroaig 15 Year Old', wb:'87', lo:170000, hi:250000},
  {b:'lagavulin', m:['12','special release','스페셜릴리즈'], age:'12', abv:'56.5', name_en:'Lagavulin 12 Year Old Special Release', wb:'89', lo:250000, hi:380000,
   cask:'Refill American Oak (캐스크 스트렝스)'},
  {b:'lagavulin', m:['distillers edition','디스틸러스에디션','de'], age:'16', abv:'43', name_en:'Lagavulin Distillers Edition', wb:'88', lo:200000, hi:290000,
   cask:'Ex-Bourbon → PX Sherry Finish'},
  {b:'bowmore', m:['18'], age:'18', abv:'43', name_en:'Bowmore 18 Year Old', wb:'88', lo:250000, hi:360000},
  {b:'caolila', m:['distillers edition','디스틸러스에디션'], age:'NAS', abv:'43', name_en:'Caol Ila Distillers Edition', wb:'87', lo:150000, hi:220000,
   cask:'Ex-Bourbon → Moscatel Finish'},
  {b:'bunnahabhain', m:['12'], age:'12', abv:'46.3', name_en:'Bunnahabhain 12 Year Old', wb:'86', lo:100000, hi:145000},
  {b:'bruichladdich', m:['classic laddie','클래식래디','래디'], age:'NAS', abv:'50', name_en:'Bruichladdich The Classic Laddie', wb:'85', lo:100000, hi:145000},
  {b:'portcharlotte', m:['10'], age:'10', abv:'50', name_en:'Port Charlotte 10 Year Old', wb:'87', lo:120000, hi:175000},
  {b:'kilchoman', m:['machir bay','마키어베이','마키르베이'], age:'NAS', abv:'46', name_en:'Kilchoman Machir Bay', wb:'86', lo:110000, hi:160000},
  {b:'talisker', m:['18'], age:'18', abv:'45.8', name_en:'Talisker 18 Year Old', wb:'89', lo:300000, hi:450000},
  {b:'talisker', m:['distillers edition','디스틸러스에디션'], age:'NAS', abv:'45.8', name_en:'Talisker Distillers Edition', wb:'87', lo:150000, hi:220000},
  {b:'talisker', m:['storm','스톰'], age:'NAS', abv:'45.8', name_en:'Talisker Storm', wb:'84', lo:90000, hi:130000},
  {b:'highlandpark', m:['15'], age:'15', abv:'44', name_en:'Highland Park 15 Year Old', wb:'86', lo:180000, hi:260000},
  {b:'highlandpark', m:['cask strength','캐스크스트렝스','cs'], age:'NAS', abv:'63', name_en:'Highland Park Cask Strength (배치 미지정)', wb:'88', lo:150000, hi:220000,
   cask:'Sherry Seasoned Oak (캐스크 스트렝스)', note:'⚠ 배치별 도수 62~65%.'},
  {b:'springbank', m:['12','cask strength','캐스크스트렝스'], age:'12', abv:'55', name_en:'Springbank 12 Year Old Cask Strength (배치 미지정)', wb:'89', lo:250000, hi:400000,
   note:'⚠ 배치별 도수 53~57%. 국내 유통이 적어 시세 변동이 큽니다.'},
  {b:'kilkerran', m:['12'], age:'12', abv:'46', name_en:'Kilkerran 12 Year Old', wb:'87', lo:130000, hi:200000},
  {b:'kilkerran', m:['8','cask strength','캐스크스트렝스'], age:'8', abv:'56', name_en:'Kilkerran 8 Year Old Cask Strength (배치 미지정)', wb:'88', lo:150000, hi:230000},
  {b:'arran', m:['10'], age:'10', abv:'46', name_en:'Arran 10 Year Old', wb:'84', lo:80000, hi:115000},
  {b:'ledaig', m:['10'], age:'10', abv:'46.3', name_en:'Ledaig 10 Year Old', wb:'86', lo:90000, hi:130000},
  // ── Japanese / World
  {b:'yamazaki', m:['18'], age:'18', abv:'43', name_en:'Suntory Yamazaki 18 Year Old', wb:'91', lo:1500000, hi:2500000,
   note:'국내 시세 변동이 매우 큽니다. 구매 시점 시세를 확인하세요.'},
  {b:'hakushu', m:['ds','distillers','디스틸러스'], age:'NAS', abv:'43', name_en:"Suntory Hakushu Distiller's Reserve", wb:'83', lo:180000, hi:280000},
  {b:'hibiki', m:['17'], age:'17', abv:'43', name_en:'Suntory Hibiki 17 Year Old', wb:'90', lo:1200000, hi:2000000},
  {b:'miyagikyo', m:['single malt','싱글몰트'], age:'NAS', abv:'45', name_en:'Nikka Miyagikyo Single Malt', wb:'85', lo:130000, hi:190000},
  {b:'taketsuru', m:['pure malt','퓨어몰트'], age:'NAS', abv:'43', name_en:'Nikka Taketsuru Pure Malt', wb:'84', lo:120000, hi:180000},
  {b:'fuji', m:['single blended','싱글블렌디드'], age:'NAS', abv:'43', name_en:'Fuji Single Blended Japanese Whisky', wb:'85', lo:130000, hi:190000},
  {b:'chichibu', m:['on the way','온더웨이'], age:'NAS', abv:'55.5', name_en:'Chichibu On The Way', wb:'89', lo:600000, hi:1000000},
  {b:'kavalan', m:['sherry oak','셰리오크'], age:'NAS', abv:'46', name_en:'Kavalan Sherry Oak', wb:'87', lo:200000, hi:300000},
  {b:'kavalan', m:['concertmaster','콘서트마스터'], age:'NAS', abv:'40', name_en:'Kavalan Concertmaster Port Cask', wb:'84', lo:130000, hi:190000},
  {b:'amrut', m:['fusion','퓨전'], age:'NAS', abv:'50', name_en:'Amrut Fusion', wb:'87', lo:130000, hi:190000},
  {b:'pauljohn', m:['brilliance','브릴리언스'], age:'NAS', abv:'46', name_en:'Paul John Brilliance', wb:'85', lo:100000, hi:150000},
  {b:'indri', m:['trini','트리니'], age:'NAS', abv:'46', name_en:'Indri Trini The Three Wood', wb:'85', lo:90000, hi:130000},
  {b:'starward', m:['nova','노바'], age:'NAS', abv:'41', name_en:'Starward Nova', wb:'84', lo:110000, hi:160000},
  {b:'penderyn', m:['madeira','마데이라'], age:'NAS', abv:'46', name_en:'Penderyn Madeira Finish', wb:'83', lo:110000, hi:160000},
  {b:'bimber', m:['oloroso','올로로소'], age:'NAS', abv:'51.5', name_en:'Bimber Oloroso Sherry Cask', wb:'88', lo:250000, hi:380000},
  {b:'cotswolds', m:['signature','시그니처'], age:'NAS', abv:'46', name_en:'Cotswolds Signature Single Malt', wb:'85', lo:110000, hi:160000},
  // ── Irish / Blends
  {b:'redbreast', m:['15'], age:'15', abv:'46', name_en:'Redbreast 15 Year Old', wb:'89', lo:220000, hi:330000},
  {b:'redbreast', m:['lustau'], age:'NAS', abv:'46', name_en:'Redbreast Lustau Edition', wb:'87', lo:150000, hi:220000},
  {b:'greenspot', m:['leoville','레오빌'], age:'NAS', abv:'46', name_en:'Green Spot Château Léoville Barton', wb:'87', lo:180000, hi:260000},
  {b:'bushmills', m:['16'], age:'16', abv:'40', name_en:'Bushmills 16 Year Old', wb:'86', lo:200000, hi:300000},
  {b:'teeling', m:['small batch','스몰배치'], age:'NAS', abv:'46', name_en:'Teeling Small Batch', wb:'82', lo:60000, hi:90000},
  {b:'connemara', m:['peated','피티드','오리지널'], age:'NAS', abv:'40', name_en:'Connemara Peated Single Malt', wb:'83', lo:80000, hi:115000},
  {b:'johnniewalker', m:['18'], age:'18', abv:'40', name_en:'Johnnie Walker 18 Year Old', wb:'85', lo:130000, hi:190000},
  {b:'johnniewalker', m:['gold','골드','골드라벨'], age:'NAS', abv:'40', name_en:'Johnnie Walker Gold Label Reserve', wb:'83', lo:90000, hi:130000},
  {b:'ballantines', m:['17'], age:'17', abv:'40', name_en:"Ballantine's 17 Year Old", wb:'85', lo:120000, hi:180000},
  {b:'ballantines', m:['21'], age:'21', abv:'40', name_en:"Ballantine's 21 Year Old", wb:'87', lo:250000, hi:380000},
  {b:'dewars', m:['12'], age:'12', abv:'40', name_en:"Dewar's 12 Year Old", wb:'80', lo:50000, hi:75000},
  {b:'famousgrouse', m:['smoky black','스모키블랙'], age:'NAS', abv:'40', name_en:'The Famous Grouse Smoky Black', wb:'78', lo:35000, hi:55000},
  {b:'nakedmalt', m:['naked','네이키드'], age:'NAS', abv:'40', name_en:'Naked Malt Blended Malt', wb:'80', lo:50000, hi:75000},
  {b:'compassbox', m:['spice tree','스파이스트리'], age:'NAS', abv:'46', name_en:'Compass Box The Spice Tree', wb:'86', lo:130000, hi:190000},
  {b:'compassbox', m:['artists blend','아티스트블렌드'], age:'NAS', abv:'43', name_en:"Compass Box Artist's Blend", wb:'85', lo:110000, hi:160000},
  {b:'royalsalute', m:['21'], age:'21', abv:'40', name_en:'Royal Salute 21 Year Old', wb:'85', lo:250000, hi:380000},
];
{
  const seen = new Set(BRANDS.map(b => b.k));
  for (const p of PRODUCTS_MORE) if (seen.has(p.b)) PRODUCTS.push(p);
}

/* ── 사용자 실구매 목록 기반 보강 (2026-07-29) ───────────────
   보유 중인 제품을 이름만으로 찾을 수 있게 등록. 한정판·단독 병입은
   도수를 비워 두고 라벨 확인 문구를 넣는다(추측하지 않는다). */
BRANDS.push({
  k:'nomad', en:'Nomad', ko:'노마드', alias:['nomad outland','노마드아웃랜드'],
  region:'Blend', country:'스코틀랜드 / 스페인', type:'Blended Scotch', wiki:'',
  cask:'Sherry Cask (헤레스 추가 숙성)',
  house:{nose:'셰리, 말린 과일, 견과', taste:'셰리 과실과 몰트, 부드러운 스파이스',
    finish:'중간 길이의 셰리 여운'},
});
BRANDS.push(
  {k:'turntable', en:'Turntable', ko:'턴테이블', alias:['turntable spirits'],
   region:'Blend', country:'스코틀랜드', type:'Blended Malt', wiki:'',
   cask:'Refill/First-fill Cask (Track 시리즈별 상이)',
   house:{nose:'과실, 바닐라, 몰트', taste:'몰트와 과실의 균형, 부드러운 오크',
     finish:'중간 길이의 마무리'}},
  {k:'noahsmill', en:"Noah's Mill", ko:'노아스밀', alias:['노아스 밀','noahs mill'],
   region:'Kentucky', country:'미국', type:'Bourbon', wiki:'Willett_Distillery',
   cask:'New Charred American Oak (스몰 배치 블렌딩)',
   house:{nose:'캐러멜, 오크, 체리, 스파이스', taste:'진한 오크와 캐러멜, 라이 스파이스, 가죽',
     finish:'길고 뜨거운 오크 마무리'}},
  {k:'fercullen', en:'Fercullen', ko:'퍼컬렌', alias:['powerscourt','파워스코트'],
   region:'Ireland', country:'아일랜드', type:'Irish', wiki:'Powerscourt_Distillery',
   cask:'Ex-Bourbon Cask',
   house:{nose:'배·사과, 크림, 시리얼', taste:'부드러운 과실과 바닐라, 크리미한 질감',
     finish:'중간 길이의 매끄러운 마무리'}},
  {k:'cameronbridge', en:'Cameronbridge', ko:'캐머런브릿지', alias:['캐머런브리지','cameron bridge'],
   region:'Lowland', country:'스코틀랜드', type:'Single Grain', wiki:'Cameronbridge_distillery',
   cask:'Ex-Bourbon Cask',
   house:{nose:'바닐라, 캐러멜, 코코넛, 시리얼', taste:'부드러운 그레인 단맛, 바닐라, 오크',
     finish:'중간 길이의 달콤한 마무리'}},
);
const PRODUCTS_MINE = [
  {b:'eaglerare', m:['10'], age:'10', abv:'45', name_en:'Eagle Rare 10 Year Old', wb:'85', lo:75000, hi:130000},
  {b:'bladnoch', m:['vinaya','비나야'], age:'NAS', abv:'46.7', name_en:'Bladnoch Vinaya', wb:'84', lo:55000, hi:85000,
   cask:'First-fill Ex-Bourbon + First-fill Sherry'},
  {b:'bladnoch', m:['11'], age:'11', abv:'46.7', name_en:'Bladnoch 11 Year Old', wb:'85', lo:90000, hi:130000},
  {b:'noahsmill', m:['noahs','노아스밀','노아스 밀'], age:'NAS', abv:'57.15', name_en:"Noah's Mill", wb:'85', lo:95000, hi:140000},
  {b:'glassaugh', m:['sandend','샌드엔드'], age:'NAS', abv:'50.5', name_en:'Glenglassaugh Sandend', wb:'86', lo:75000, hi:110000,
   cask:'Ex-Bourbon + Sherry + Manzanilla Sherry Cask'},
  {b:'glassaugh', m:['12'], age:'12', abv:'45', name_en:'Glenglassaugh 12 Year Old', wb:'86', lo:110000, hi:160000},
  {b:'balvenie', m:['single barrel','싱글배럴'], age:'12', abv:'47.8', name_en:'The Balvenie Single Barrel 12 Year Old First Fill', wb:'86', lo:120000, hi:170000,
   cask:'First-fill Ex-Bourbon Barrel (Single Barrel)', note:'⚠ 싱글 배럴 — 배럴마다 풍미가 다릅니다.'},
  {b:'inchgower', m:['14'], age:'14', abv:'43', name_en:'Inchgower 14 Year Old (Flora & Fauna)', wb:'84', lo:70000, hi:105000},
  {b:'evanwilliams', m:['12'], age:'12', abv:'50.5', name_en:'Evan Williams 12 Year Old', wb:'86', lo:75000, hi:110000},
  {b:'fercullen', m:['18'], age:'18', abv:'', name_en:'Fercullen 18 Year Old', lo:130000, hi:180000,
   note:'⚠ 도수를 라벨에서 확인해 주세요.'},
  {b:'turntable', m:['track','트랙','트렉'], age:'NAS', abv:'', name_en:'Turntable Track Series', lo:70000, hi:100000,
   note:'⚠ Track 번호별로 구성 몰트와 도수가 다릅니다. 라벨 확인 필요.'},
  {b:'omar', m:['sherry','셰리'], age:'NAS', abv:'46', name_en:'Omar Sherry Cask', wb:'86', lo:80000, hi:120000,
   cask:'Sherry Cask'},
  {b:'linkwood', m:['12'], age:'12', abv:'46', name_en:'Linkwood 12 Year Old', wb:'85', lo:120000, hi:170000},
  {b:'cameronbridge', m:['26'], age:'26', abv:'', name_en:'Cameronbridge 26 Year Old Special Release', lo:200000, hi:300000,
   note:'⚠ Special Release — 도수·캐스크는 라벨 확인 필요.'},
  {b:'starward', m:['fortis','포티스'], age:'NAS', abv:'50', name_en:'Starward Fortis', wb:'85', lo:100000, hi:130000,
   cask:'Australian Red Wine Barrel (100%)',
   nose:'붉은 과일, 자두, 바닐라, 초콜릿', taste:'농밀한 붉은 와인 캐스크의 과실감, 몰트 단맛, 스파이스',
   finish:'중간~긴 길이, 달콤한 오크와 탄닌'},
  {b:'starward', m:['nova','노바'], age:'NAS', abv:'41', name_en:'Starward Nova', wb:'84', lo:110000, hi:160000,
   cask:'Australian Red Wine Barrel'},
  {b:'starward', m:['tawny','타니','타우니'], age:'NAS', abv:'', name_en:'Starward Tawny Cask', lo:120000, hi:160000,
   cask:'Tawny (Port) Cask', note:'⚠ 도수는 라벨을 확인해 채워 주세요.'},
  {b:'starward', m:['lagavulin','라가불린캐스크'], age:'NAS', abv:'', name_en:'Starward Lagavulin Cask', lo:130000, hi:180000,
   cask:'Ex-Lagavulin Cask (피티드)', note:'⚠ 한정 라인 — 도수는 라벨 확인 필요.'},
  {b:'jackdaniels', m:['gentleman','젠틀맨','젠틀맨잭'], age:'NAS', abv:'40', name_en:"Jack Daniel's Gentleman Jack", wb:'77', lo:38000, hi:55000,
   cask:'New Charred American Oak (숯 여과 2회)'},
  {b:'evanwilliams', m:['bib','bottled in bond','본디드'], age:'NAS', abv:'50', name_en:'Evan Williams Bottled in Bond', wb:'84', lo:28000, hi:45000,
   cask:'New Charred American Oak (Bottled in Bond)'},
  {b:'jura', m:['18'], age:'18', abv:'44', name_en:'Jura 18 Year Old', wb:'86', lo:150000, hi:220000,
   cask:'Ex-Bourbon → Red Wine Cask Finish'},
  {b:'jura', m:['10'], age:'10', abv:'40', name_en:'Jura 10 Year Old', wb:'80', lo:70000, hi:100000},
  {b:'jura', m:['12'], age:'12', abv:'40', name_en:'Jura 12 Year Old', wb:'83', lo:90000, hi:130000},
  {b:'royalbrackla', m:['18'], age:'18', abv:'46', name_en:'Royal Brackla 18 Year Old', wb:'86', lo:180000, hi:260000,
   cask:'Ex-Bourbon → Oloroso Sherry Cask Finish'},
  {b:'royalbrackla', m:['12'], age:'12', abv:'46', name_en:'Royal Brackla 12 Year Old', wb:'84', lo:100000, hi:145000},
  {b:'milkhoney', m:['elements','엘리먼츠','sherry','셰리'], age:'NAS', abv:'46', name_en:'Milk & Honey Elements Sherry Cask', wb:'84', lo:70000, hi:95000,
   cask:'Ex-Bourbon → Sherry Cask',
   nose:'건포도, 무화과, 오렌지 껍질, 꿀', taste:'셰리 과실과 몰트, 대추, 스파이스',
   finish:'중간 길이, 달콤한 셰리 여운'},
  {b:'milkhoney', m:['dead sea','사해'], age:'NAS', abv:'', name_en:'Milk & Honey Dead Sea Cask Strength', lo:110000, hi:150000,
   cask:'Cask Strength (사해 저지대 숙성)',
   note:'⚠ 캐스크 스트렝스 — 도수는 배치별로 다릅니다. 해수면 아래 고온·고압 환경 숙성 라인.'},
  {b:'milkhoney', m:['classic','클래식'], age:'NAS', abv:'46', name_en:'Milk & Honey Classic Single Malt', wb:'82', lo:60000, hi:85000},
  {b:'amrut', m:['peated','피티드'], age:'NAS', abv:'46', name_en:'Amrut Peated Single Malt', wb:'86', lo:110000, hi:150000,
   cask:'Ex-Bourbon Cask (피티드)'},
  {b:'amrut', m:['peated cs','피티드cs','cask strength','캐스크스트렝스'], age:'NAS', abv:'62.8',
   name_en:'Amrut Peated Cask Strength', wb:'88', lo:120000, hi:170000,
   cask:'Ex-Bourbon Cask (피티드 · 캐스크 스트렝스)',
   nose:'피트 스모크, 몰트, 열대 과일, 바닐라', taste:'강한 스모크와 농축된 몰트, 후추, 열대 과실',
   finish:'길고 강렬한 스모크와 오크',
   note:'⚠ 62.8%는 표준 표기값 — 배치에 따라 다를 수 있어 라벨 확인 권장.'},
  /* '싱글톤'만으로는 12년/15년/17년 구분이 안 되므로 매칭 토큰에서 제외한다 */
  {b:'glenord', m:['12'], age:'12', abv:'40', name_en:'The Singleton of Glen Ord 12 Year Old', wb:'83', lo:80000, hi:115000},
  {b:'glenord', m:['15'], age:'15', abv:'40', name_en:'The Singleton of Glen Ord 15 Year Old', wb:'85', lo:130000, hi:190000},
  {b:'glenord', m:['18'], age:'18', abv:'40', name_en:'The Singleton of Glen Ord 18 Year Old', wb:'87', lo:200000, hi:290000},
  {b:'nomad', m:['nomad','노마드','outland'], age:'NAS', abv:'41.3', name_en:'Nomad Outland Whisky', wb:'82', lo:60000, hi:95000,
   cask:'Ex-Bourbon + Sherry → 헤레스에서 PX 셰리 캐스크 추가 숙성',
   note:'⚠ "노마드 10" 표기라면 다른 라인일 수 있습니다. 라벨을 확인해 주세요.'},
  {b:'teaninich', m:['10'], age:'10', abv:'43', name_en:'Teaninich 10 Year Old', wb:'82', lo:70000, hi:100000},
  {b:'glengoyne', m:['18'], age:'18', abv:'43', name_en:'Glengoyne 18 Year Old', wb:'87', lo:200000, hi:290000},
  {b:'glengoyne', m:['21'], age:'21', abv:'43', name_en:'Glengoyne 21 Year Old', wb:'88', lo:300000, hi:450000},
  {b:'caolila', m:['moch','모크'], age:'NAS', abv:'43', name_en:'Caol Ila Moch', wb:'84', lo:90000, hi:130000},
];
{
  const seen = new Set(BRANDS.map(b => b.k));
  for (const p of PRODUCTS_MINE) if (seen.has(p.b)) PRODUCTS.push(p);
}

/* ── 제품 표현명 한글 별칭 보강 ──────────────────────────────
   "아부나흐" "우거달" "블루라벨" 처럼 증류소 없이 표현명만 부르는 경우가 많다.
   이 별칭이 있어야 제품명만으로도 검색된다. */
const PRODUCT_ALIASES = {
  "Aberlour A'bunadh (배치 미지정)": ['아부나흐','아분아흐','어부나흐','아부나','아분아'],
  'Ardbeg Uigeadail': ['우거달','우가달','위게아달'],
  'Ardbeg Corryvreckan': ['코리브레칸','코리브레컨','코리브렉칸'],
  'Ardbeg 10 Year Old': ['아드벡텐'],
  'Laphroaig Quarter Cask': ['쿼터캐스크','쿼터 캐스크','쿼터캐스트'],
  'Glenmorangie Lasanta 12 Year Old': ['라산타'],
  'Glenmorangie Quinta Ruban 14 Year Old': ['퀸타루반','퀸타 루반','퀸타'],
  "Glenmorangie Nectar d'Or": ['넥타도르','넥타 도르','넥타'],
  'Glenmorangie The Original 10 Year Old': ['오리지널10'],
  'The Balvenie DoubleWood 12 Year Old': ['더블우드','더블 우드'],
  'The Balvenie Caribbean Cask 14 Year Old': ['캐리비안캐스크','캐리비안','캐리비언'],
  'The Macallan Double Cask 12 Years Old': ['더블캐스크','더블 캐스크'],
  'The Macallan Sherry Oak 12 Years Old': ['셰리오크','쉐리오크'],
  'The Glenlivet 15 Year Old French Oak Reserve': ['프렌치오크'],
  'Glenfiddich 15 Year Old Solera': ['솔레라'],
  'Glenfarclas 105 Cask Strength': ['글렌파클라스105'],
  'The GlenDronach 15 Year Old Revival': ['리바이벌'],
  'The GlenDronach 18 Year Old Allardice': ['알라디스','알라다이스'],
  'The GlenDronach 12 Year Old Original': ['글렌드로낙오리지널'],
  'Highland Park 12 Year Old Viking Honour': ['바이킹아너','바이킹'],
  'Talisker Skye': ['스카이'],
  'Suntory Yamazaki 12 Year Old': ['야마자키12'],
  "Suntory Yamazaki Distiller's Reserve": ['디스틸러스리저브','디스틸러스','야마자키DR'],
  'Suntory Hibiki Japanese Harmony': ['하모니','하머니','재패니즈하모니'],
  'Nikka From The Barrel': ['프롬더배럴','프롬 더 배럴','프롬더바렐','후로무더바렐'],
  'Nikka Yoichi Single Malt': ['요이치싱글몰트'],
  "Maker's Mark Kentucky Straight Bourbon": ['메이커스마크'],
  'Buffalo Trace Kentucky Straight Bourbon': ['버팔로트레이스','버팔로'],
  'Woodford Reserve Double Oaked': ['더블오크드','더블오크'],
  'Wild Turkey Rare Breed': ['레어브리드','레어 브리드'],
  'Wild Turkey 101': ['와일드터키101'],
  'Eagle Rare 10 Year Old': ['이글레어'],
  "Blanton's Original Single Barrel": ['블랑톤오리지널','블랜튼오리지널'],
  'Elijah Craig Small Batch': ['엘리야크레이그스몰배치'],
  'Four Roses Small Batch': ['포로지스스몰배치'],
  'Johnnie Walker Black Label 12 Year Old': ['블랙라벨','조니워커블랙'],
  'Johnnie Walker Green Label 15 Year Old': ['그린라벨','조니워커그린'],
  'Johnnie Walker Blue Label': ['블루라벨','조니워커블루'],
  'Chivas Regal 18 Year Old': ['시바스18'],
  'Monkey Shoulder Blended Malt': ['몽키숄더'],
  'Kavalan Classic Single Malt': ['카발란클래식'],
  'Kavalan Solist (캐스크 미지정)': ['솔리스트'],
  'Redbreast 12 Year Old': ['레드브레스트12'],
  'Jameson Irish Whiskey': ['제임슨오리지널'],
  'GlenAllachie 10 Year Old Cask Strength (배치 미지정)': ['글렌알라키10CS'],
  'Lagavulin 16 Year Old': ['라가불린16'],
  'Springbank 10 Year Old': ['스프링뱅크10'],
};
for (const p of PRODUCTS){
  const extra = PRODUCT_ALIASES[p.name_en];
  if (extra) p.m = [...new Set([...(p.m || []), ...extra])];
}

/* 브랜드 키 → 브랜드 객체 */
const BRAND_BY_KEY = Object.fromEntries(BRANDS.map(b => [b.k, b]));
